/* The Internal catalog. Generated by scripts/gen-shadcn-registry.ts from
   packages/internal/src/components/ui and site/src/docs/internal — do not edit; add a
   demo under site/src/examples/internal/ or a doc under site/src/docs/internal/ and run
   the script. */
import { lazy } from "react";
import type { Pkg } from "../types";
import ButtonDemoSrc from "../examples/internal/ButtonDemo.tsx?raw";
import ButtonGroupDemoSrc from "../examples/internal/ButtonGroupDemo.tsx?raw";
import ToggleDemoSrc from "../examples/internal/ToggleDemo.tsx?raw";
import ToggleGroupDemoSrc from "../examples/internal/ToggleGroupDemo.tsx?raw";
import KbdDemoSrc from "../examples/internal/KbdDemo.tsx?raw";
import InputDemoSrc from "../examples/internal/InputDemo.tsx?raw";
import InputGroupDemoSrc from "../examples/internal/InputGroupDemo.tsx?raw";
import InputOtpDemoSrc from "../examples/internal/InputOtpDemo.tsx?raw";
import TextareaDemoSrc from "../examples/internal/TextareaDemo.tsx?raw";
import LabelDemoSrc from "../examples/internal/LabelDemo.tsx?raw";
import FieldDemoSrc from "../examples/internal/FieldDemo.tsx?raw";
import CheckboxDemoSrc from "../examples/internal/CheckboxDemo.tsx?raw";
import RadioGroupDemoSrc from "../examples/internal/RadioGroupDemo.tsx?raw";
import SwitchDemoSrc from "../examples/internal/SwitchDemo.tsx?raw";
import SelectDemoSrc from "../examples/internal/SelectDemo.tsx?raw";
import NativeSelectDemoSrc from "../examples/internal/NativeSelectDemo.tsx?raw";
import ComboboxDemoSrc from "../examples/internal/ComboboxDemo.tsx?raw";
import SliderDemoSrc from "../examples/internal/SliderDemo.tsx?raw";
import CalendarDemoSrc from "../examples/internal/CalendarDemo.tsx?raw";
import QuestionnaireDemoSrc from "../examples/internal/QuestionnaireDemo.tsx?raw";
import DialogDemoSrc from "../examples/internal/DialogDemo.tsx?raw";
import AlertDialogDemoSrc from "../examples/internal/AlertDialogDemo.tsx?raw";
import SheetDemoSrc from "../examples/internal/SheetDemo.tsx?raw";
import DrawerDemoSrc from "../examples/internal/DrawerDemo.tsx?raw";
import PopoverDemoSrc from "../examples/internal/PopoverDemo.tsx?raw";
import HoverCardDemoSrc from "../examples/internal/HoverCardDemo.tsx?raw";
import TooltipDemoSrc from "../examples/internal/TooltipDemo.tsx?raw";
import DropdownMenuDemoSrc from "../examples/internal/DropdownMenuDemo.tsx?raw";
import ContextMenuDemoSrc from "../examples/internal/ContextMenuDemo.tsx?raw";
import MenubarDemoSrc from "../examples/internal/MenubarDemo.tsx?raw";
import NavigationMenuDemoSrc from "../examples/internal/NavigationMenuDemo.tsx?raw";
import CommandDemoSrc from "../examples/internal/CommandDemo.tsx?raw";
import ToastDemoSrc from "../examples/internal/ToastDemo.tsx?raw";
import AccordionDemoSrc from "../examples/internal/AccordionDemo.tsx?raw";
import CollapsibleDemoSrc from "../examples/internal/CollapsibleDemo.tsx?raw";
import TabsDemoSrc from "../examples/internal/TabsDemo.tsx?raw";
import AlertDemoSrc from "../examples/internal/AlertDemo.tsx?raw";
import BadgeDemoSrc from "../examples/internal/BadgeDemo.tsx?raw";
import StatusDotDemoSrc from "../examples/internal/StatusDotDemo.tsx?raw";
import ProgressDemoSrc from "../examples/internal/ProgressDemo.tsx?raw";
import GaugeDemoSrc from "../examples/internal/GaugeDemo.tsx?raw";
import SpinnerDemoSrc from "../examples/internal/SpinnerDemo.tsx?raw";
import SkeletonDemoSrc from "../examples/internal/SkeletonDemo.tsx?raw";
import EmptyDemoSrc from "../examples/internal/EmptyDemo.tsx?raw";
import MarkerDemoSrc from "../examples/internal/MarkerDemo.tsx?raw";
import TableDemoSrc from "../examples/internal/TableDemo.tsx?raw";
import ChartDemoSrc from "../examples/internal/ChartDemo.tsx?raw";
import DescriptionDemoSrc from "../examples/internal/DescriptionDemo.tsx?raw";
import SnippetDemoSrc from "../examples/internal/SnippetDemo.tsx?raw";
import PaginationDemoSrc from "../examples/internal/PaginationDemo.tsx?raw";
import BreadcrumbDemoSrc from "../examples/internal/BreadcrumbDemo.tsx?raw";
import AvatarDemoSrc from "../examples/internal/AvatarDemo.tsx?raw";
import CardDemoSrc from "../examples/internal/CardDemo.tsx?raw";
import ItemDemoSrc from "../examples/internal/ItemDemo.tsx?raw";
import CarouselDemoSrc from "../examples/internal/CarouselDemo.tsx?raw";
import SeparatorDemoSrc from "../examples/internal/SeparatorDemo.tsx?raw";
import AspectRatioDemoSrc from "../examples/internal/AspectRatioDemo.tsx?raw";
import ScrollAreaDemoSrc from "../examples/internal/ScrollAreaDemo.tsx?raw";
import ResizableDemoSrc from "../examples/internal/ResizableDemo.tsx?raw";
import SidebarDemoSrc from "../examples/internal/SidebarDemo.tsx?raw";
import DirectionDemoSrc from "../examples/internal/DirectionDemo.tsx?raw";
import MessageDemoSrc from "../examples/internal/MessageDemo.tsx?raw";
import MessageScrollerDemoSrc from "../examples/internal/MessageScrollerDemo.tsx?raw";
import BubbleDemoSrc from "../examples/internal/BubbleDemo.tsx?raw";
import AttachmentDemoSrc from "../examples/internal/AttachmentDemo.tsx?raw";
import ButtonDoc from "../docs/internal/button";
import ButtonSizeSrc from "../examples/internal/button/size.tsx?raw";
import ButtonDefaultSrc from "../examples/internal/button/default.tsx?raw";
import ButtonOutlineSrc from "../examples/internal/button/outline.tsx?raw";
import ButtonSecondarySrc from "../examples/internal/button/secondary.tsx?raw";
import ButtonGhostSrc from "../examples/internal/button/ghost.tsx?raw";
import ButtonDestructiveSrc from "../examples/internal/button/destructive.tsx?raw";
import ButtonLinkSrc from "../examples/internal/button/link.tsx?raw";
import ButtonIconSrc from "../examples/internal/button/icon.tsx?raw";
import ButtonWithIconSrc from "../examples/internal/button/with-icon.tsx?raw";
import ButtonSpinnerSrc from "../examples/internal/button/spinner.tsx?raw";
import ButtonGroupSrc from "../examples/internal/button/group.tsx?raw";
import ButtonAsLinkSrc from "../examples/internal/button/as-link.tsx?raw";
import InputDoc from "../docs/internal/input";
import InputBasicSrc from "../examples/internal/input/basic.tsx?raw";
import InputFieldSrc from "../examples/internal/input/field.tsx?raw";
import InputFieldGroupSrc from "../examples/internal/input/field-group.tsx?raw";
import InputDisabledSrc from "../examples/internal/input/disabled.tsx?raw";
import InputInvalidSrc from "../examples/internal/input/invalid.tsx?raw";
import InputFileSrc from "../examples/internal/input/file.tsx?raw";
import InputInlineSrc from "../examples/internal/input/inline.tsx?raw";
import InputGridSrc from "../examples/internal/input/grid.tsx?raw";
import InputRequiredSrc from "../examples/internal/input/required.tsx?raw";
import InputBadgeSrc from "../examples/internal/input/badge.tsx?raw";
import InputInputGroupSrc from "../examples/internal/input/input-group.tsx?raw";
import InputButtonGroupSrc from "../examples/internal/input/button-group.tsx?raw";
import InputFormSrc from "../examples/internal/input/form.tsx?raw";
import SelectDoc from "../docs/internal/select";
import SelectAlignItemSrc from "../examples/internal/select/align-item.tsx?raw";
import SelectGroupsSrc from "../examples/internal/select/groups.tsx?raw";
import SelectScrollableSrc from "../examples/internal/select/scrollable.tsx?raw";
import SelectSmallSrc from "../examples/internal/select/small.tsx?raw";
import SelectDisabledSrc from "../examples/internal/select/disabled.tsx?raw";
import SelectInvalidSrc from "../examples/internal/select/invalid.tsx?raw";
import SelectControlledSrc from "../examples/internal/select/controlled.tsx?raw";
import DialogDoc from "../docs/internal/dialog";
import DialogCloseButtonSrc from "../examples/internal/dialog/close-button.tsx?raw";
import DialogFooterCloseSrc from "../examples/internal/dialog/footer-close.tsx?raw";
import DialogNoCloseButtonSrc from "../examples/internal/dialog/no-close-button.tsx?raw";
import DialogStickyFooterSrc from "../examples/internal/dialog/sticky-footer.tsx?raw";
import DialogScrollableContentSrc from "../examples/internal/dialog/scrollable-content.tsx?raw";
import DialogControlledSrc from "../examples/internal/dialog/controlled.tsx?raw";
import TableDoc from "../docs/internal/table";
import TableCaptionSrc from "../examples/internal/table/caption.tsx?raw";
import TableFooterSrc from "../examples/internal/table/footer.tsx?raw";
import TableActionsSrc from "../examples/internal/table/actions.tsx?raw";
import TableSelectionSrc from "../examples/internal/table/selection.tsx?raw";

export const internal: Pkg = {
  id: "internal",
  name: "Internal",
  pkg: "@ovadev-gmbh/ui-internal",
  frame: true,
  groups: ["Actions", "Forms", "Overlays", "Disclosure", "Feedback", "Data", "Layout", "Chat"],
  entries: [
    {
      name: "Button",
      slug: "button",
      group: "Actions",
      imports: ["Button"],
      examples: [
        { Component: lazy(() => import("../examples/internal/ButtonDemo")), source: ButtonDemoSrc },
        { name: "size", Component: lazy(() => import("../examples/internal/button/size")), source: ButtonSizeSrc },
        { name: "default", Component: lazy(() => import("../examples/internal/button/default")), source: ButtonDefaultSrc },
        { name: "outline", Component: lazy(() => import("../examples/internal/button/outline")), source: ButtonOutlineSrc },
        { name: "secondary", Component: lazy(() => import("../examples/internal/button/secondary")), source: ButtonSecondarySrc },
        { name: "ghost", Component: lazy(() => import("../examples/internal/button/ghost")), source: ButtonGhostSrc },
        { name: "destructive", Component: lazy(() => import("../examples/internal/button/destructive")), source: ButtonDestructiveSrc },
        { name: "link", Component: lazy(() => import("../examples/internal/button/link")), source: ButtonLinkSrc },
        { name: "icon", Component: lazy(() => import("../examples/internal/button/icon")), source: ButtonIconSrc },
        { name: "with-icon", Component: lazy(() => import("../examples/internal/button/with-icon")), source: ButtonWithIconSrc },
        { name: "spinner", Component: lazy(() => import("../examples/internal/button/spinner")), source: ButtonSpinnerSrc },
        { name: "group", Component: lazy(() => import("../examples/internal/button/group")), source: ButtonGroupSrc },
        { name: "as-link", Component: lazy(() => import("../examples/internal/button/as-link")), source: ButtonAsLinkSrc },
      ],
      doc: ButtonDoc,
    },
    {
      name: "Button Group",
      slug: "button-group",
      group: "Actions",
      imports: ["ButtonGroup","ButtonGroupSeparator","ButtonGroupText"],
      examples: [{ Component: lazy(() => import("../examples/internal/ButtonGroupDemo")), source: ButtonGroupDemoSrc }],
    },
    {
      name: "Toggle",
      slug: "toggle",
      group: "Actions",
      imports: ["Toggle"],
      examples: [{ Component: lazy(() => import("../examples/internal/ToggleDemo")), source: ToggleDemoSrc }],
    },
    {
      name: "Toggle Group",
      slug: "toggle-group",
      group: "Actions",
      imports: ["ToggleGroup","ToggleGroupItem"],
      examples: [{ Component: lazy(() => import("../examples/internal/ToggleGroupDemo")), source: ToggleGroupDemoSrc }],
    },
    {
      name: "Kbd",
      slug: "kbd",
      group: "Actions",
      imports: ["Kbd","KbdGroup"],
      examples: [{ Component: lazy(() => import("../examples/internal/KbdDemo")), source: KbdDemoSrc }],
    },
    {
      name: "Input",
      slug: "input",
      group: "Forms",
      imports: ["Input"],
      examples: [
        { Component: lazy(() => import("../examples/internal/InputDemo")), source: InputDemoSrc },
        { name: "basic", Component: lazy(() => import("../examples/internal/input/basic")), source: InputBasicSrc },
        { name: "field", Component: lazy(() => import("../examples/internal/input/field")), source: InputFieldSrc },
        { name: "field-group", Component: lazy(() => import("../examples/internal/input/field-group")), source: InputFieldGroupSrc },
        { name: "disabled", Component: lazy(() => import("../examples/internal/input/disabled")), source: InputDisabledSrc },
        { name: "invalid", Component: lazy(() => import("../examples/internal/input/invalid")), source: InputInvalidSrc },
        { name: "file", Component: lazy(() => import("../examples/internal/input/file")), source: InputFileSrc },
        { name: "inline", Component: lazy(() => import("../examples/internal/input/inline")), source: InputInlineSrc },
        { name: "grid", Component: lazy(() => import("../examples/internal/input/grid")), source: InputGridSrc },
        { name: "required", Component: lazy(() => import("../examples/internal/input/required")), source: InputRequiredSrc },
        { name: "badge", Component: lazy(() => import("../examples/internal/input/badge")), source: InputBadgeSrc },
        { name: "input-group", Component: lazy(() => import("../examples/internal/input/input-group")), source: InputInputGroupSrc },
        { name: "button-group", Component: lazy(() => import("../examples/internal/input/button-group")), source: InputButtonGroupSrc },
        { name: "form", Component: lazy(() => import("../examples/internal/input/form")), source: InputFormSrc },
      ],
      doc: InputDoc,
    },
    {
      name: "Input Group",
      slug: "input-group",
      group: "Forms",
      imports: ["InputGroup","InputGroupAddon","InputGroupButton","InputGroupText","InputGroupInput","InputGroupTextarea"],
      examples: [{ Component: lazy(() => import("../examples/internal/InputGroupDemo")), source: InputGroupDemoSrc }],
    },
    {
      name: "Input OTP",
      slug: "input-otp",
      group: "Forms",
      imports: ["InputOTP","InputOTPGroup","InputOTPSlot","InputOTPSeparator"],
      examples: [{ Component: lazy(() => import("../examples/internal/InputOtpDemo")), source: InputOtpDemoSrc }],
    },
    {
      name: "Textarea",
      slug: "textarea",
      group: "Forms",
      imports: ["Textarea"],
      examples: [{ Component: lazy(() => import("../examples/internal/TextareaDemo")), source: TextareaDemoSrc }],
    },
    {
      name: "Label",
      slug: "label",
      group: "Forms",
      imports: ["Label"],
      examples: [{ Component: lazy(() => import("../examples/internal/LabelDemo")), source: LabelDemoSrc }],
    },
    {
      name: "Field",
      slug: "field",
      group: "Forms",
      imports: ["Field","FieldLabel","FieldDescription","FieldError","FieldGroup","FieldLegend","FieldSeparator","FieldSet","FieldContent","FieldTitle"],
      examples: [{ Component: lazy(() => import("../examples/internal/FieldDemo")), source: FieldDemoSrc }],
    },
    {
      name: "Checkbox",
      slug: "checkbox",
      group: "Forms",
      imports: ["Checkbox"],
      examples: [{ Component: lazy(() => import("../examples/internal/CheckboxDemo")), source: CheckboxDemoSrc }],
    },
    {
      name: "Radio Group",
      slug: "radio-group",
      group: "Forms",
      imports: ["RadioGroup","RadioGroupItem"],
      examples: [{ Component: lazy(() => import("../examples/internal/RadioGroupDemo")), source: RadioGroupDemoSrc }],
    },
    {
      name: "Switch",
      slug: "switch",
      group: "Forms",
      imports: ["Switch"],
      examples: [{ Component: lazy(() => import("../examples/internal/SwitchDemo")), source: SwitchDemoSrc }],
    },
    {
      name: "Select",
      slug: "select",
      group: "Forms",
      imports: ["Select","SelectContent","SelectGroup","SelectItem","SelectLabel","SelectScrollDownButton","SelectScrollUpButton","SelectSeparator","SelectTrigger","SelectValue"],
      examples: [
        { Component: lazy(() => import("../examples/internal/SelectDemo")), source: SelectDemoSrc },
        { name: "align-item", Component: lazy(() => import("../examples/internal/select/align-item")), source: SelectAlignItemSrc },
        { name: "groups", Component: lazy(() => import("../examples/internal/select/groups")), source: SelectGroupsSrc },
        { name: "scrollable", Component: lazy(() => import("../examples/internal/select/scrollable")), source: SelectScrollableSrc },
        { name: "small", Component: lazy(() => import("../examples/internal/select/small")), source: SelectSmallSrc },
        { name: "disabled", Component: lazy(() => import("../examples/internal/select/disabled")), source: SelectDisabledSrc },
        { name: "invalid", Component: lazy(() => import("../examples/internal/select/invalid")), source: SelectInvalidSrc },
        { name: "controlled", Component: lazy(() => import("../examples/internal/select/controlled")), source: SelectControlledSrc },
      ],
      doc: SelectDoc,
    },
    {
      name: "Native Select",
      slug: "native-select",
      group: "Forms",
      imports: ["NativeSelect","NativeSelectOptGroup","NativeSelectOption"],
      examples: [{ Component: lazy(() => import("../examples/internal/NativeSelectDemo")), source: NativeSelectDemoSrc }],
    },
    {
      name: "Combobox",
      slug: "combobox",
      group: "Forms",
      imports: ["Combobox","ComboboxInput","ComboboxContent","ComboboxList","ComboboxItem","ComboboxGroup","ComboboxLabel","ComboboxCollection","ComboboxEmpty","ComboboxSeparator","ComboboxChips","ComboboxChip","ComboboxChipsInput","ComboboxTrigger","ComboboxValue"],
      examples: [{ Component: lazy(() => import("../examples/internal/ComboboxDemo")), source: ComboboxDemoSrc }],
    },
    {
      name: "Slider",
      slug: "slider",
      group: "Forms",
      imports: ["Slider"],
      examples: [{ Component: lazy(() => import("../examples/internal/SliderDemo")), source: SliderDemoSrc }],
    },
    {
      name: "Calendar",
      slug: "calendar",
      group: "Forms",
      imports: ["Calendar","CalendarDayButton"],
      examples: [{ Component: lazy(() => import("../examples/internal/CalendarDemo")), source: CalendarDemoSrc }],
    },
    {
      name: "Questionnaire",
      slug: "questionnaire",
      group: "Forms",
      imports: ["Questionnaire","QuestionnaireActions","QuestionnaireChoice","QuestionnaireChoiceDescription","QuestionnaireChoices","QuestionnaireDescription","QuestionnaireError","QuestionnaireInput","QuestionnaireItem","QuestionnaireNext","QuestionnairePrevious","QuestionnaireProgress","QuestionnaireSkip","QuestionnaireSubmit","QuestionnaireTitle"],
      examples: [{ Component: lazy(() => import("../examples/internal/QuestionnaireDemo")), source: QuestionnaireDemoSrc }],
    },
    {
      name: "Dialog",
      slug: "dialog",
      group: "Overlays",
      imports: ["Dialog","DialogClose","DialogContent","DialogDescription","DialogFooter","DialogHeader","DialogOverlay","DialogPortal","DialogTitle","DialogTrigger"],
      examples: [
        { Component: lazy(() => import("../examples/internal/DialogDemo")), source: DialogDemoSrc },
        { name: "close-button", Component: lazy(() => import("../examples/internal/dialog/close-button")), source: DialogCloseButtonSrc },
        { name: "footer-close", Component: lazy(() => import("../examples/internal/dialog/footer-close")), source: DialogFooterCloseSrc },
        { name: "no-close-button", Component: lazy(() => import("../examples/internal/dialog/no-close-button")), source: DialogNoCloseButtonSrc },
        { name: "sticky-footer", Component: lazy(() => import("../examples/internal/dialog/sticky-footer")), source: DialogStickyFooterSrc },
        { name: "scrollable-content", Component: lazy(() => import("../examples/internal/dialog/scrollable-content")), source: DialogScrollableContentSrc },
        { name: "controlled", Component: lazy(() => import("../examples/internal/dialog/controlled")), source: DialogControlledSrc },
      ],
      doc: DialogDoc,
    },
    {
      name: "Alert Dialog",
      slug: "alert-dialog",
      group: "Overlays",
      imports: ["AlertDialog","AlertDialogAction","AlertDialogCancel","AlertDialogContent","AlertDialogDescription","AlertDialogFooter","AlertDialogHeader","AlertDialogMedia","AlertDialogOverlay","AlertDialogPortal","AlertDialogTitle","AlertDialogTrigger"],
      examples: [{ Component: lazy(() => import("../examples/internal/AlertDialogDemo")), source: AlertDialogDemoSrc }],
    },
    {
      name: "Sheet",
      slug: "sheet",
      group: "Overlays",
      imports: ["Sheet","SheetTrigger","SheetClose","SheetContent","SheetHeader","SheetFooter","SheetTitle","SheetDescription"],
      examples: [{ Component: lazy(() => import("../examples/internal/SheetDemo")), source: SheetDemoSrc }],
    },
    {
      name: "Drawer",
      slug: "drawer",
      group: "Overlays",
      imports: ["Drawer","DrawerPortal","DrawerOverlay","DrawerSwipeHandle","DrawerTrigger","DrawerClose","DrawerContent","DrawerHeader","DrawerFooter","DrawerTitle","DrawerDescription"],
      examples: [{ Component: lazy(() => import("../examples/internal/DrawerDemo")), source: DrawerDemoSrc }],
    },
    {
      name: "Popover",
      slug: "popover",
      group: "Overlays",
      imports: ["Popover","PopoverContent","PopoverDescription","PopoverHeader","PopoverTitle","PopoverTrigger"],
      examples: [{ Component: lazy(() => import("../examples/internal/PopoverDemo")), source: PopoverDemoSrc }],
    },
    {
      name: "Hover Card",
      slug: "hover-card",
      group: "Overlays",
      imports: ["HoverCard","HoverCardTrigger","HoverCardContent"],
      examples: [{ Component: lazy(() => import("../examples/internal/HoverCardDemo")), source: HoverCardDemoSrc }],
    },
    {
      name: "Tooltip",
      slug: "tooltip",
      group: "Overlays",
      imports: ["Tooltip","TooltipTrigger","TooltipContent","TooltipProvider"],
      examples: [{ Component: lazy(() => import("../examples/internal/TooltipDemo")), source: TooltipDemoSrc }],
    },
    {
      name: "Dropdown Menu",
      slug: "dropdown-menu",
      group: "Overlays",
      imports: ["DropdownMenu","DropdownMenuPortal","DropdownMenuTrigger","DropdownMenuContent","DropdownMenuGroup","DropdownMenuLabel","DropdownMenuItem","DropdownMenuCheckboxItem","DropdownMenuRadioGroup","DropdownMenuRadioItem","DropdownMenuSeparator","DropdownMenuShortcut","DropdownMenuSub","DropdownMenuSubTrigger","DropdownMenuSubContent"],
      examples: [{ Component: lazy(() => import("../examples/internal/DropdownMenuDemo")), source: DropdownMenuDemoSrc }],
    },
    {
      name: "Context Menu",
      slug: "context-menu",
      group: "Overlays",
      imports: ["ContextMenu","ContextMenuTrigger","ContextMenuContent","ContextMenuItem","ContextMenuCheckboxItem","ContextMenuRadioItem","ContextMenuLabel","ContextMenuSeparator","ContextMenuShortcut","ContextMenuGroup","ContextMenuPortal","ContextMenuSub","ContextMenuSubContent","ContextMenuSubTrigger","ContextMenuRadioGroup"],
      examples: [{ Component: lazy(() => import("../examples/internal/ContextMenuDemo")), source: ContextMenuDemoSrc }],
    },
    {
      name: "Menubar",
      slug: "menubar",
      group: "Overlays",
      imports: ["Menubar","MenubarPortal","MenubarMenu","MenubarTrigger","MenubarContent","MenubarGroup","MenubarSeparator","MenubarLabel","MenubarItem","MenubarShortcut","MenubarCheckboxItem","MenubarRadioGroup","MenubarRadioItem","MenubarSub","MenubarSubTrigger","MenubarSubContent"],
      examples: [{ Component: lazy(() => import("../examples/internal/MenubarDemo")), source: MenubarDemoSrc }],
    },
    {
      name: "Navigation Menu",
      slug: "navigation-menu",
      group: "Overlays",
      imports: ["NavigationMenu","NavigationMenuContent","NavigationMenuIndicator","NavigationMenuItem","NavigationMenuLink","NavigationMenuList","NavigationMenuTrigger","NavigationMenuPositioner"],
      examples: [{ Component: lazy(() => import("../examples/internal/NavigationMenuDemo")), source: NavigationMenuDemoSrc }],
    },
    {
      name: "Command",
      slug: "command",
      group: "Overlays",
      imports: ["Command","CommandDialog","CommandInput","CommandList","CommandEmpty","CommandGroup","CommandItem","CommandShortcut","CommandSeparator"],
      examples: [{ Component: lazy(() => import("../examples/internal/CommandDemo")), source: CommandDemoSrc }],
    },
    {
      name: "Toast",
      slug: "toast",
      group: "Overlays",
      imports: ["Toaster","Toast","ToastAction","ToastClose","ToastContent","ToastDescription","ToastPortal","ToastProvider","ToastTitle","ToastViewport"],
      examples: [{ Component: lazy(() => import("../examples/internal/ToastDemo")), source: ToastDemoSrc }],
    },
    {
      name: "Accordion",
      slug: "accordion",
      group: "Disclosure",
      imports: ["Accordion","AccordionItem","AccordionTrigger","AccordionContent"],
      examples: [{ Component: lazy(() => import("../examples/internal/AccordionDemo")), source: AccordionDemoSrc }],
    },
    {
      name: "Collapsible",
      slug: "collapsible",
      group: "Disclosure",
      imports: ["Collapsible","CollapsibleTrigger","CollapsibleContent"],
      examples: [{ Component: lazy(() => import("../examples/internal/CollapsibleDemo")), source: CollapsibleDemoSrc }],
    },
    {
      name: "Tabs",
      slug: "tabs",
      group: "Disclosure",
      imports: ["Tabs","TabsList","TabsTrigger","TabsContent"],
      examples: [{ Component: lazy(() => import("../examples/internal/TabsDemo")), source: TabsDemoSrc }],
    },
    {
      name: "Alert",
      slug: "alert",
      group: "Feedback",
      imports: ["Alert","AlertTitle","AlertDescription","AlertAction"],
      examples: [{ Component: lazy(() => import("../examples/internal/AlertDemo")), source: AlertDemoSrc }],
    },
    {
      name: "Badge",
      slug: "badge",
      group: "Feedback",
      imports: ["Badge"],
      examples: [{ Component: lazy(() => import("../examples/internal/BadgeDemo")), source: BadgeDemoSrc }],
    },
    {
      name: "Status Dot",
      slug: "status-dot",
      group: "Feedback",
      imports: ["StatusDot"],
      examples: [{ Component: lazy(() => import("../examples/internal/StatusDotDemo")), source: StatusDotDemoSrc }],
    },
    {
      name: "Progress",
      slug: "progress",
      group: "Feedback",
      imports: ["Progress","ProgressTrack","ProgressIndicator","ProgressLabel","ProgressValue"],
      examples: [{ Component: lazy(() => import("../examples/internal/ProgressDemo")), source: ProgressDemoSrc }],
    },
    {
      name: "Gauge",
      slug: "gauge",
      group: "Feedback",
      imports: ["Gauge"],
      examples: [{ Component: lazy(() => import("../examples/internal/GaugeDemo")), source: GaugeDemoSrc }],
    },
    {
      name: "Spinner",
      slug: "spinner",
      group: "Feedback",
      imports: ["Spinner"],
      examples: [{ Component: lazy(() => import("../examples/internal/SpinnerDemo")), source: SpinnerDemoSrc }],
    },
    {
      name: "Skeleton",
      slug: "skeleton",
      group: "Feedback",
      imports: ["Skeleton"],
      examples: [{ Component: lazy(() => import("../examples/internal/SkeletonDemo")), source: SkeletonDemoSrc }],
    },
    {
      name: "Empty",
      slug: "empty",
      group: "Feedback",
      imports: ["Empty","EmptyHeader","EmptyTitle","EmptyDescription","EmptyContent","EmptyMedia"],
      examples: [{ Component: lazy(() => import("../examples/internal/EmptyDemo")), source: EmptyDemoSrc }],
    },
    {
      name: "Marker",
      slug: "marker",
      group: "Feedback",
      imports: ["Marker","MarkerIcon","MarkerContent"],
      examples: [{ Component: lazy(() => import("../examples/internal/MarkerDemo")), source: MarkerDemoSrc }],
    },
    {
      name: "Table",
      slug: "table",
      group: "Data",
      imports: ["Table","TableHeader","TableBody","TableFooter","TableHead","TableRow","TableCell","TableCaption"],
      examples: [
        { Component: lazy(() => import("../examples/internal/TableDemo")), source: TableDemoSrc },
        { name: "caption", Component: lazy(() => import("../examples/internal/table/caption")), source: TableCaptionSrc },
        { name: "footer", Component: lazy(() => import("../examples/internal/table/footer")), source: TableFooterSrc },
        { name: "actions", Component: lazy(() => import("../examples/internal/table/actions")), source: TableActionsSrc },
        { name: "selection", Component: lazy(() => import("../examples/internal/table/selection")), source: TableSelectionSrc },
      ],
      doc: TableDoc,
    },
    {
      name: "Chart",
      slug: "chart",
      group: "Data",
      imports: ["ChartContainer","ChartTooltip","ChartTooltipContent","ChartLegend","ChartLegendContent","ChartStyle"],
      examples: [{ Component: lazy(() => import("../examples/internal/ChartDemo")), source: ChartDemoSrc }],
    },
    {
      name: "Description",
      slug: "description",
      group: "Data",
      imports: ["Description","DescriptionList"],
      examples: [{ Component: lazy(() => import("../examples/internal/DescriptionDemo")), source: DescriptionDemoSrc }],
    },
    {
      name: "Snippet",
      slug: "snippet",
      group: "Data",
      imports: ["Snippet","SecretValue"],
      examples: [{ Component: lazy(() => import("../examples/internal/SnippetDemo")), source: SnippetDemoSrc }],
    },
    {
      name: "Pagination",
      slug: "pagination",
      group: "Data",
      imports: ["Pagination","PaginationContent","PaginationEllipsis","PaginationItem","PaginationLink","PaginationNext","PaginationPrevious"],
      examples: [{ Component: lazy(() => import("../examples/internal/PaginationDemo")), source: PaginationDemoSrc }],
    },
    {
      name: "Breadcrumb",
      slug: "breadcrumb",
      group: "Data",
      imports: ["Breadcrumb","BreadcrumbList","BreadcrumbItem","BreadcrumbLink","BreadcrumbPage","BreadcrumbSeparator","BreadcrumbEllipsis"],
      examples: [{ Component: lazy(() => import("../examples/internal/BreadcrumbDemo")), source: BreadcrumbDemoSrc }],
    },
    {
      name: "Avatar",
      slug: "avatar",
      group: "Data",
      imports: ["Avatar","AvatarImage","AvatarFallback","AvatarGroup","AvatarGroupCount","AvatarBadge"],
      examples: [{ Component: lazy(() => import("../examples/internal/AvatarDemo")), source: AvatarDemoSrc }],
    },
    {
      name: "Card",
      slug: "card",
      group: "Data",
      imports: ["Card","CardHeader","CardFooter","CardTitle","CardAction","CardDescription","CardContent"],
      examples: [{ Component: lazy(() => import("../examples/internal/CardDemo")), source: CardDemoSrc }],
    },
    {
      name: "Item",
      slug: "item",
      group: "Data",
      imports: ["Item","ItemMedia","ItemContent","ItemActions","ItemGroup","ItemSeparator","ItemTitle","ItemDescription","ItemHeader","ItemFooter"],
      examples: [{ Component: lazy(() => import("../examples/internal/ItemDemo")), source: ItemDemoSrc }],
    },
    {
      name: "Carousel",
      slug: "carousel",
      group: "Data",
      imports: ["CarouselApi","Carousel","CarouselContent","CarouselItem","CarouselPrevious","CarouselNext"],
      examples: [{ Component: lazy(() => import("../examples/internal/CarouselDemo")), source: CarouselDemoSrc }],
    },
    {
      name: "Separator",
      slug: "separator",
      group: "Layout",
      imports: ["Separator"],
      examples: [{ Component: lazy(() => import("../examples/internal/SeparatorDemo")), source: SeparatorDemoSrc }],
    },
    {
      name: "Aspect Ratio",
      slug: "aspect-ratio",
      group: "Layout",
      imports: ["AspectRatio"],
      examples: [{ Component: lazy(() => import("../examples/internal/AspectRatioDemo")), source: AspectRatioDemoSrc }],
    },
    {
      name: "Scroll Area",
      slug: "scroll-area",
      group: "Layout",
      imports: ["ScrollArea","ScrollBar"],
      examples: [{ Component: lazy(() => import("../examples/internal/ScrollAreaDemo")), source: ScrollAreaDemoSrc }],
    },
    {
      name: "Resizable",
      slug: "resizable",
      group: "Layout",
      imports: ["ResizableHandle","ResizablePanel","ResizablePanelGroup"],
      examples: [{ Component: lazy(() => import("../examples/internal/ResizableDemo")), source: ResizableDemoSrc }],
    },
    {
      name: "Sidebar",
      slug: "sidebar",
      group: "Layout",
      imports: ["Sidebar","SidebarContent","SidebarFooter","SidebarGroup","SidebarGroupAction","SidebarGroupContent","SidebarGroupLabel","SidebarHeader","SidebarInput","SidebarInset","SidebarMenu","SidebarMenuAction","SidebarMenuBadge","SidebarMenuButton","SidebarMenuItem","SidebarMenuSkeleton","SidebarMenuSub","SidebarMenuSubButton","SidebarMenuSubItem","SidebarProvider","SidebarRail","SidebarSeparator","SidebarTrigger"],
      examples: [{ Component: lazy(() => import("../examples/internal/SidebarDemo")), source: SidebarDemoSrc }],
    },
    {
      name: "Direction",
      slug: "direction",
      group: "Layout",
      imports: [],
      examples: [{ Component: lazy(() => import("../examples/internal/DirectionDemo")), source: DirectionDemoSrc }],
    },
    {
      name: "Message",
      slug: "message",
      group: "Chat",
      imports: ["MessageGroup","Message","MessageAvatar","MessageContent","MessageFooter","MessageHeader"],
      examples: [{ Component: lazy(() => import("../examples/internal/MessageDemo")), source: MessageDemoSrc }],
    },
    {
      name: "Message Scroller",
      slug: "message-scroller",
      group: "Chat",
      imports: ["MessageScrollerProvider","MessageScroller","MessageScrollerViewport","MessageScrollerContent","MessageScrollerItem","MessageScrollerButton"],
      examples: [{ Component: lazy(() => import("../examples/internal/MessageScrollerDemo")), source: MessageScrollerDemoSrc }],
    },
    {
      name: "Bubble",
      slug: "bubble",
      group: "Chat",
      imports: ["BubbleGroup","Bubble","BubbleContent","BubbleReactions"],
      examples: [{ Component: lazy(() => import("../examples/internal/BubbleDemo")), source: BubbleDemoSrc }],
    },
    {
      name: "Attachment",
      slug: "attachment",
      group: "Chat",
      imports: ["Attachment","AttachmentGroup","AttachmentMedia","AttachmentContent","AttachmentTitle","AttachmentDescription","AttachmentActions","AttachmentAction","AttachmentTrigger"],
      examples: [{ Component: lazy(() => import("../examples/internal/AttachmentDemo")), source: AttachmentDemoSrc }],
    },
  ],
};
