/* The Base UI half of this package's catalog: one page per component, each
   showing Base UI's own demo unstyled. Generated by scripts/gen-baseui.ts —
   the hand-written entries live in januna.ts next to this file. */
import type { Entry } from "../types";
import AccordionBasic from "../examples/januna/AccordionBasic";
import AccordionBasicSrc from "../examples/januna/AccordionBasic.tsx?raw";
import AlertDialogBasic from "../examples/januna/AlertDialogBasic";
import AlertDialogBasicSrc from "../examples/januna/AlertDialogBasic.tsx?raw";
import AutocompleteBasic from "../examples/januna/AutocompleteBasic";
import AutocompleteBasicSrc from "../examples/januna/AutocompleteBasic.tsx?raw";
import AvatarBasic from "../examples/januna/AvatarBasic";
import AvatarBasicSrc from "../examples/januna/AvatarBasic.tsx?raw";
import ButtonBasic from "../examples/januna/ButtonBasic";
import ButtonBasicSrc from "../examples/januna/ButtonBasic.tsx?raw";
import CheckboxGroupBasic from "../examples/januna/CheckboxGroupBasic";
import CheckboxGroupBasicSrc from "../examples/januna/CheckboxGroupBasic.tsx?raw";
import CheckboxBasic from "../examples/januna/CheckboxBasic";
import CheckboxBasicSrc from "../examples/januna/CheckboxBasic.tsx?raw";
import CollapsibleBasic from "../examples/januna/CollapsibleBasic";
import CollapsibleBasicSrc from "../examples/januna/CollapsibleBasic.tsx?raw";
import ComboboxBasic from "../examples/januna/ComboboxBasic";
import ComboboxBasicSrc from "../examples/januna/ComboboxBasic.tsx?raw";
import ContextMenuBasic from "../examples/januna/ContextMenuBasic";
import ContextMenuBasicSrc from "../examples/januna/ContextMenuBasic.tsx?raw";
import DialogBasic from "../examples/januna/DialogBasic";
import DialogBasicSrc from "../examples/januna/DialogBasic.tsx?raw";
import DrawerBasic from "../examples/januna/DrawerBasic";
import DrawerBasicSrc from "../examples/januna/DrawerBasic.tsx?raw";
import FieldBasic from "../examples/januna/FieldBasic";
import FieldBasicSrc from "../examples/januna/FieldBasic.tsx?raw";
import FieldsetBasic from "../examples/januna/FieldsetBasic";
import FieldsetBasicSrc from "../examples/januna/FieldsetBasic.tsx?raw";
import FormBasic from "../examples/januna/FormBasic";
import FormBasicSrc from "../examples/januna/FormBasic.tsx?raw";
import InputBasic from "../examples/januna/InputBasic";
import InputBasicSrc from "../examples/januna/InputBasic.tsx?raw";
import MenuBasic from "../examples/januna/MenuBasic";
import MenuBasicSrc from "../examples/januna/MenuBasic.tsx?raw";
import MenubarBasic from "../examples/januna/MenubarBasic";
import MenubarBasicSrc from "../examples/januna/MenubarBasic.tsx?raw";
import MeterBasic from "../examples/januna/MeterBasic";
import MeterBasicSrc from "../examples/januna/MeterBasic.tsx?raw";
import NavigationMenuBasic from "../examples/januna/NavigationMenuBasic";
import NavigationMenuBasicSrc from "../examples/januna/NavigationMenuBasic.tsx?raw";
import NumberFieldBasic from "../examples/januna/NumberFieldBasic";
import NumberFieldBasicSrc from "../examples/januna/NumberFieldBasic.tsx?raw";
import OtpFieldBasic from "../examples/januna/OtpFieldBasic";
import OtpFieldBasicSrc from "../examples/januna/OtpFieldBasic.tsx?raw";
import PopoverBasic from "../examples/januna/PopoverBasic";
import PopoverBasicSrc from "../examples/januna/PopoverBasic.tsx?raw";
import PreviewCardBasic from "../examples/januna/PreviewCardBasic";
import PreviewCardBasicSrc from "../examples/januna/PreviewCardBasic.tsx?raw";
import ProgressBasic from "../examples/januna/ProgressBasic";
import ProgressBasicSrc from "../examples/januna/ProgressBasic.tsx?raw";
import RadioBasic from "../examples/januna/RadioBasic";
import RadioBasicSrc from "../examples/januna/RadioBasic.tsx?raw";
import ScrollAreaBasic from "../examples/januna/ScrollAreaBasic";
import ScrollAreaBasicSrc from "../examples/januna/ScrollAreaBasic.tsx?raw";
import SelectBasic from "../examples/januna/SelectBasic";
import SelectBasicSrc from "../examples/januna/SelectBasic.tsx?raw";
import SeparatorBasic from "../examples/januna/SeparatorBasic";
import SeparatorBasicSrc from "../examples/januna/SeparatorBasic.tsx?raw";
import SliderBasic from "../examples/januna/SliderBasic";
import SliderBasicSrc from "../examples/januna/SliderBasic.tsx?raw";
import SwitchBasic from "../examples/januna/SwitchBasic";
import SwitchBasicSrc from "../examples/januna/SwitchBasic.tsx?raw";
import TabsBasic from "../examples/januna/TabsBasic";
import TabsBasicSrc from "../examples/januna/TabsBasic.tsx?raw";
import ToastBasic from "../examples/januna/ToastBasic";
import ToastBasicSrc from "../examples/januna/ToastBasic.tsx?raw";
import ToggleGroupBasic from "../examples/januna/ToggleGroupBasic";
import ToggleGroupBasicSrc from "../examples/januna/ToggleGroupBasic.tsx?raw";
import ToggleBasic from "../examples/januna/ToggleBasic";
import ToggleBasicSrc from "../examples/januna/ToggleBasic.tsx?raw";
import ToolbarBasic from "../examples/januna/ToolbarBasic";
import ToolbarBasicSrc from "../examples/januna/ToolbarBasic.tsx?raw";
import TooltipBasic from "../examples/januna/TooltipBasic";
import TooltipBasicSrc from "../examples/januna/TooltipBasic.tsx?raw";

export const BASE_UI_GROUPS = ["Actions","Forms","Overlays","Disclosure","Feedback","Layout"];

export const baseUiEntries: Entry[] = [
  {
    name: "Button",
    slug: "button",
    group: "Actions",
    imports: ["Button"],
    examples: [
      {
        Component: ButtonBasic,
        source: ButtonBasicSrc,
      },
    ],
  },
  {
    name: "Toggle",
    slug: "toggle",
    group: "Actions",
    imports: ["Toggle"],
    examples: [
      {
        Component: ToggleBasic,
        source: ToggleBasicSrc,
      },
    ],
  },
  {
    name: "Toggle Group",
    slug: "toggle-group",
    group: "Actions",
    imports: ["ToggleGroup"],
    examples: [
      {
        Component: ToggleGroupBasic,
        source: ToggleGroupBasicSrc,
      },
    ],
  },
  {
    name: "Toolbar",
    slug: "toolbar",
    group: "Actions",
    imports: ["Toolbar"],
    examples: [
      {
        Component: ToolbarBasic,
        source: ToolbarBasicSrc,
      },
    ],
  },
  {
    name: "Autocomplete",
    slug: "autocomplete",
    group: "Forms",
    imports: ["Autocomplete"],
    examples: [
      {
        Component: AutocompleteBasic,
        source: AutocompleteBasicSrc,
      },
    ],
  },
  {
    name: "Checkbox",
    slug: "checkbox",
    group: "Forms",
    imports: ["Checkbox"],
    examples: [
      {
        Component: CheckboxBasic,
        source: CheckboxBasicSrc,
      },
    ],
  },
  {
    name: "Checkbox Group",
    slug: "checkbox-group",
    group: "Forms",
    imports: ["CheckboxGroup"],
    examples: [
      {
        Component: CheckboxGroupBasic,
        source: CheckboxGroupBasicSrc,
      },
    ],
  },
  {
    name: "Combobox",
    slug: "combobox",
    group: "Forms",
    imports: ["Combobox"],
    examples: [
      {
        Component: ComboboxBasic,
        source: ComboboxBasicSrc,
      },
    ],
  },
  {
    name: "Field",
    slug: "field",
    group: "Forms",
    imports: ["Field"],
    examples: [
      {
        Component: FieldBasic,
        source: FieldBasicSrc,
      },
    ],
  },
  {
    name: "Fieldset",
    slug: "fieldset",
    group: "Forms",
    imports: ["Fieldset"],
    examples: [
      {
        Component: FieldsetBasic,
        source: FieldsetBasicSrc,
      },
    ],
  },
  {
    name: "Form",
    slug: "form",
    group: "Forms",
    imports: ["Form"],
    examples: [
      {
        Component: FormBasic,
        source: FormBasicSrc,
      },
    ],
  },
  {
    name: "Input",
    slug: "input",
    group: "Forms",
    imports: ["Input"],
    examples: [
      {
        Component: InputBasic,
        source: InputBasicSrc,
      },
    ],
  },
  {
    name: "Number Field",
    slug: "number-field",
    group: "Forms",
    imports: ["NumberField"],
    examples: [
      {
        Component: NumberFieldBasic,
        source: NumberFieldBasicSrc,
      },
    ],
  },
  {
    name: "OTP Field",
    slug: "otp-field",
    group: "Forms",
    imports: ["OTPField"],
    examples: [
      {
        Component: OtpFieldBasic,
        source: OtpFieldBasicSrc,
      },
    ],
  },
  {
    name: "Radio",
    slug: "radio",
    group: "Forms",
    imports: ["Radio","RadioGroup"],
    examples: [
      {
        Component: RadioBasic,
        source: RadioBasicSrc,
      },
    ],
  },
  {
    name: "Select",
    slug: "select",
    group: "Forms",
    imports: ["Select"],
    examples: [
      {
        Component: SelectBasic,
        source: SelectBasicSrc,
      },
    ],
  },
  {
    name: "Slider",
    slug: "slider",
    group: "Forms",
    imports: ["Slider"],
    examples: [
      {
        Component: SliderBasic,
        source: SliderBasicSrc,
      },
    ],
  },
  {
    name: "Switch",
    slug: "switch",
    group: "Forms",
    imports: ["Switch"],
    examples: [
      {
        Component: SwitchBasic,
        source: SwitchBasicSrc,
      },
    ],
  },
  {
    name: "Alert Dialog",
    slug: "alert-dialog",
    group: "Overlays",
    imports: ["AlertDialog"],
    examples: [
      {
        Component: AlertDialogBasic,
        source: AlertDialogBasicSrc,
      },
    ],
  },
  {
    name: "Context Menu",
    slug: "context-menu",
    group: "Overlays",
    imports: ["ContextMenu"],
    examples: [
      {
        Component: ContextMenuBasic,
        source: ContextMenuBasicSrc,
      },
    ],
  },
  {
    name: "Dialog",
    slug: "dialog",
    group: "Overlays",
    imports: ["Dialog"],
    examples: [
      {
        Component: DialogBasic,
        source: DialogBasicSrc,
      },
    ],
  },
  {
    name: "Drawer",
    slug: "drawer",
    group: "Overlays",
    imports: ["Drawer"],
    examples: [
      {
        Component: DrawerBasic,
        source: DrawerBasicSrc,
      },
    ],
  },
  {
    name: "Menu",
    slug: "menu",
    group: "Overlays",
    imports: ["Menu"],
    examples: [
      {
        Component: MenuBasic,
        source: MenuBasicSrc,
      },
    ],
  },
  {
    name: "Menubar",
    slug: "menubar",
    group: "Overlays",
    imports: ["Menubar"],
    examples: [
      {
        Component: MenubarBasic,
        source: MenubarBasicSrc,
      },
    ],
  },
  {
    name: "Navigation Menu",
    slug: "navigation-menu",
    group: "Overlays",
    imports: ["NavigationMenu"],
    examples: [
      {
        Component: NavigationMenuBasic,
        source: NavigationMenuBasicSrc,
      },
    ],
  },
  {
    name: "Popover",
    slug: "popover",
    group: "Overlays",
    imports: ["Popover"],
    examples: [
      {
        Component: PopoverBasic,
        source: PopoverBasicSrc,
      },
    ],
  },
  {
    name: "Preview Card",
    slug: "preview-card",
    group: "Overlays",
    imports: ["PreviewCard"],
    examples: [
      {
        Component: PreviewCardBasic,
        source: PreviewCardBasicSrc,
      },
    ],
  },
  {
    name: "Toast",
    slug: "toast",
    group: "Overlays",
    imports: ["Toast"],
    examples: [
      {
        Component: ToastBasic,
        source: ToastBasicSrc,
      },
    ],
  },
  {
    name: "Tooltip",
    slug: "tooltip",
    group: "Overlays",
    imports: ["Tooltip"],
    examples: [
      {
        Component: TooltipBasic,
        source: TooltipBasicSrc,
      },
    ],
  },
  {
    name: "Accordion",
    slug: "accordion",
    group: "Disclosure",
    imports: ["Accordion"],
    examples: [
      {
        Component: AccordionBasic,
        source: AccordionBasicSrc,
      },
    ],
  },
  {
    name: "Collapsible",
    slug: "collapsible",
    group: "Disclosure",
    imports: ["Collapsible"],
    examples: [
      {
        Component: CollapsibleBasic,
        source: CollapsibleBasicSrc,
      },
    ],
  },
  {
    name: "Tabs",
    slug: "tabs",
    group: "Disclosure",
    imports: ["Tabs"],
    examples: [
      {
        Component: TabsBasic,
        source: TabsBasicSrc,
      },
    ],
  },
  {
    name: "Meter",
    slug: "meter",
    group: "Feedback",
    imports: ["Meter"],
    examples: [
      {
        Component: MeterBasic,
        source: MeterBasicSrc,
      },
    ],
  },
  {
    name: "Progress",
    slug: "progress",
    group: "Feedback",
    imports: ["Progress"],
    examples: [
      {
        Component: ProgressBasic,
        source: ProgressBasicSrc,
      },
    ],
  },
  {
    name: "Avatar",
    slug: "avatar",
    group: "Layout",
    imports: ["Avatar"],
    examples: [
      {
        Component: AvatarBasic,
        source: AvatarBasicSrc,
      },
    ],
  },
  {
    name: "Scroll Area",
    slug: "scroll-area",
    group: "Layout",
    imports: ["ScrollArea"],
    examples: [
      {
        Component: ScrollAreaBasic,
        source: ScrollAreaBasicSrc,
      },
    ],
  },
  {
    name: "Separator",
    slug: "separator",
    group: "Layout",
    imports: ["Separator"],
    examples: [
      {
        Component: SeparatorBasic,
        source: SeparatorBasicSrc,
      },
    ],
  },
];
