/* The Januna catalog. Generated by scripts/gen-shadcn-registry.ts from
   packages/januna/src/components/ui — do not edit; add a demo under
   site/src/examples/januna/ and run the script. */
import { lazy } from "react";
import type { Pkg } from "../types";
import ButtonDemoSrc from "../examples/januna/ButtonDemo.tsx?raw";
import ButtonGroupDemoSrc from "../examples/januna/ButtonGroupDemo.tsx?raw";
import ToggleDemoSrc from "../examples/januna/ToggleDemo.tsx?raw";
import ToggleGroupDemoSrc from "../examples/januna/ToggleGroupDemo.tsx?raw";
import KbdDemoSrc from "../examples/januna/KbdDemo.tsx?raw";
import InputDemoSrc from "../examples/januna/InputDemo.tsx?raw";
import InputGroupDemoSrc from "../examples/januna/InputGroupDemo.tsx?raw";
import InputOtpDemoSrc from "../examples/januna/InputOtpDemo.tsx?raw";
import TextareaDemoSrc from "../examples/januna/TextareaDemo.tsx?raw";
import LabelDemoSrc from "../examples/januna/LabelDemo.tsx?raw";
import FieldDemoSrc from "../examples/januna/FieldDemo.tsx?raw";
import CheckboxDemoSrc from "../examples/januna/CheckboxDemo.tsx?raw";
import RadioGroupDemoSrc from "../examples/januna/RadioGroupDemo.tsx?raw";
import SwitchDemoSrc from "../examples/januna/SwitchDemo.tsx?raw";
import SelectDemoSrc from "../examples/januna/SelectDemo.tsx?raw";
import NativeSelectDemoSrc from "../examples/januna/NativeSelectDemo.tsx?raw";
import ComboboxDemoSrc from "../examples/januna/ComboboxDemo.tsx?raw";
import SliderDemoSrc from "../examples/januna/SliderDemo.tsx?raw";
import CalendarDemoSrc from "../examples/januna/CalendarDemo.tsx?raw";
import QuestionnaireDemoSrc from "../examples/januna/QuestionnaireDemo.tsx?raw";
import DialogDemoSrc from "../examples/januna/DialogDemo.tsx?raw";
import AlertDialogDemoSrc from "../examples/januna/AlertDialogDemo.tsx?raw";
import SheetDemoSrc from "../examples/januna/SheetDemo.tsx?raw";
import DrawerDemoSrc from "../examples/januna/DrawerDemo.tsx?raw";
import PopoverDemoSrc from "../examples/januna/PopoverDemo.tsx?raw";
import HoverCardDemoSrc from "../examples/januna/HoverCardDemo.tsx?raw";
import TooltipDemoSrc from "../examples/januna/TooltipDemo.tsx?raw";
import DropdownMenuDemoSrc from "../examples/januna/DropdownMenuDemo.tsx?raw";
import ContextMenuDemoSrc from "../examples/januna/ContextMenuDemo.tsx?raw";
import MenubarDemoSrc from "../examples/januna/MenubarDemo.tsx?raw";
import NavigationMenuDemoSrc from "../examples/januna/NavigationMenuDemo.tsx?raw";
import CommandDemoSrc from "../examples/januna/CommandDemo.tsx?raw";
import ToastDemoSrc from "../examples/januna/ToastDemo.tsx?raw";
import AccordionDemoSrc from "../examples/januna/AccordionDemo.tsx?raw";
import CollapsibleDemoSrc from "../examples/januna/CollapsibleDemo.tsx?raw";
import TabsDemoSrc from "../examples/januna/TabsDemo.tsx?raw";
import AlertDemoSrc from "../examples/januna/AlertDemo.tsx?raw";
import BadgeDemoSrc from "../examples/januna/BadgeDemo.tsx?raw";
import ProgressDemoSrc from "../examples/januna/ProgressDemo.tsx?raw";
import SpinnerDemoSrc from "../examples/januna/SpinnerDemo.tsx?raw";
import SkeletonDemoSrc from "../examples/januna/SkeletonDemo.tsx?raw";
import EmptyDemoSrc from "../examples/januna/EmptyDemo.tsx?raw";
import MarkerDemoSrc from "../examples/januna/MarkerDemo.tsx?raw";
import TableDemoSrc from "../examples/januna/TableDemo.tsx?raw";
import ChartDemoSrc from "../examples/januna/ChartDemo.tsx?raw";
import PaginationDemoSrc from "../examples/januna/PaginationDemo.tsx?raw";
import BreadcrumbDemoSrc from "../examples/januna/BreadcrumbDemo.tsx?raw";
import AvatarDemoSrc from "../examples/januna/AvatarDemo.tsx?raw";
import CardDemoSrc from "../examples/januna/CardDemo.tsx?raw";
import ItemDemoSrc from "../examples/januna/ItemDemo.tsx?raw";
import CarouselDemoSrc from "../examples/januna/CarouselDemo.tsx?raw";
import SeparatorDemoSrc from "../examples/januna/SeparatorDemo.tsx?raw";
import AspectRatioDemoSrc from "../examples/januna/AspectRatioDemo.tsx?raw";
import ScrollAreaDemoSrc from "../examples/januna/ScrollAreaDemo.tsx?raw";
import ResizableDemoSrc from "../examples/januna/ResizableDemo.tsx?raw";
import SidebarDemoSrc from "../examples/januna/SidebarDemo.tsx?raw";
import DirectionDemoSrc from "../examples/januna/DirectionDemo.tsx?raw";
import MessageDemoSrc from "../examples/januna/MessageDemo.tsx?raw";
import MessageScrollerDemoSrc from "../examples/januna/MessageScrollerDemo.tsx?raw";
import BubbleDemoSrc from "../examples/januna/BubbleDemo.tsx?raw";
import AttachmentDemoSrc from "../examples/januna/AttachmentDemo.tsx?raw";

export const januna: Pkg = {
  id: "januna",
  name: "Januna",
  pkg: "@ovadev-gmbh/ui-januna",
  frame: true,
  groups: ["Actions", "Forms", "Overlays", "Disclosure", "Feedback", "Data", "Layout", "Chat"],
  entries: [
    {
      name: "Button",
      slug: "button",
      group: "Actions",
      imports: ["Button"],
      examples: [{ Component: lazy(() => import("../examples/januna/ButtonDemo")), source: ButtonDemoSrc }],
    },
    {
      name: "Button Group",
      slug: "button-group",
      group: "Actions",
      imports: ["ButtonGroup","ButtonGroupSeparator","ButtonGroupText"],
      examples: [{ Component: lazy(() => import("../examples/januna/ButtonGroupDemo")), source: ButtonGroupDemoSrc }],
    },
    {
      name: "Toggle",
      slug: "toggle",
      group: "Actions",
      imports: ["Toggle"],
      examples: [{ Component: lazy(() => import("../examples/januna/ToggleDemo")), source: ToggleDemoSrc }],
    },
    {
      name: "Toggle Group",
      slug: "toggle-group",
      group: "Actions",
      imports: ["ToggleGroup","ToggleGroupItem"],
      examples: [{ Component: lazy(() => import("../examples/januna/ToggleGroupDemo")), source: ToggleGroupDemoSrc }],
    },
    {
      name: "Kbd",
      slug: "kbd",
      group: "Actions",
      imports: ["Kbd","KbdGroup"],
      examples: [{ Component: lazy(() => import("../examples/januna/KbdDemo")), source: KbdDemoSrc }],
    },
    {
      name: "Input",
      slug: "input",
      group: "Forms",
      imports: ["Input"],
      examples: [{ Component: lazy(() => import("../examples/januna/InputDemo")), source: InputDemoSrc }],
    },
    {
      name: "Input Group",
      slug: "input-group",
      group: "Forms",
      imports: ["InputGroup","InputGroupAddon","InputGroupButton","InputGroupText","InputGroupInput","InputGroupTextarea"],
      examples: [{ Component: lazy(() => import("../examples/januna/InputGroupDemo")), source: InputGroupDemoSrc }],
    },
    {
      name: "Input OTP",
      slug: "input-otp",
      group: "Forms",
      imports: ["InputOTP","InputOTPGroup","InputOTPSlot","InputOTPSeparator"],
      examples: [{ Component: lazy(() => import("../examples/januna/InputOtpDemo")), source: InputOtpDemoSrc }],
    },
    {
      name: "Textarea",
      slug: "textarea",
      group: "Forms",
      imports: ["Textarea"],
      examples: [{ Component: lazy(() => import("../examples/januna/TextareaDemo")), source: TextareaDemoSrc }],
    },
    {
      name: "Label",
      slug: "label",
      group: "Forms",
      imports: ["Label"],
      examples: [{ Component: lazy(() => import("../examples/januna/LabelDemo")), source: LabelDemoSrc }],
    },
    {
      name: "Field",
      slug: "field",
      group: "Forms",
      imports: ["Field","FieldLabel","FieldDescription","FieldError","FieldGroup","FieldLegend","FieldSeparator","FieldSet","FieldContent","FieldTitle"],
      examples: [{ Component: lazy(() => import("../examples/januna/FieldDemo")), source: FieldDemoSrc }],
    },
    {
      name: "Checkbox",
      slug: "checkbox",
      group: "Forms",
      imports: ["Checkbox"],
      examples: [{ Component: lazy(() => import("../examples/januna/CheckboxDemo")), source: CheckboxDemoSrc }],
    },
    {
      name: "Radio Group",
      slug: "radio-group",
      group: "Forms",
      imports: ["RadioGroup","RadioGroupItem"],
      examples: [{ Component: lazy(() => import("../examples/januna/RadioGroupDemo")), source: RadioGroupDemoSrc }],
    },
    {
      name: "Switch",
      slug: "switch",
      group: "Forms",
      imports: ["Switch"],
      examples: [{ Component: lazy(() => import("../examples/januna/SwitchDemo")), source: SwitchDemoSrc }],
    },
    {
      name: "Select",
      slug: "select",
      group: "Forms",
      imports: ["Select","SelectContent","SelectGroup","SelectItem","SelectLabel","SelectScrollDownButton","SelectScrollUpButton","SelectSeparator","SelectTrigger","SelectValue"],
      examples: [{ Component: lazy(() => import("../examples/januna/SelectDemo")), source: SelectDemoSrc }],
    },
    {
      name: "Native Select",
      slug: "native-select",
      group: "Forms",
      imports: ["NativeSelect","NativeSelectOptGroup","NativeSelectOption"],
      examples: [{ Component: lazy(() => import("../examples/januna/NativeSelectDemo")), source: NativeSelectDemoSrc }],
    },
    {
      name: "Combobox",
      slug: "combobox",
      group: "Forms",
      imports: ["Combobox","ComboboxInput","ComboboxContent","ComboboxList","ComboboxItem","ComboboxGroup","ComboboxLabel","ComboboxCollection","ComboboxEmpty","ComboboxSeparator","ComboboxChips","ComboboxChip","ComboboxChipsInput","ComboboxTrigger","ComboboxValue"],
      examples: [{ Component: lazy(() => import("../examples/januna/ComboboxDemo")), source: ComboboxDemoSrc }],
    },
    {
      name: "Slider",
      slug: "slider",
      group: "Forms",
      imports: ["Slider"],
      examples: [{ Component: lazy(() => import("../examples/januna/SliderDemo")), source: SliderDemoSrc }],
    },
    {
      name: "Calendar",
      slug: "calendar",
      group: "Forms",
      imports: ["Calendar","CalendarDayButton"],
      examples: [{ Component: lazy(() => import("../examples/januna/CalendarDemo")), source: CalendarDemoSrc }],
    },
    {
      name: "Questionnaire",
      slug: "questionnaire",
      group: "Forms",
      imports: ["Questionnaire","QuestionnaireActions","QuestionnaireChoice","QuestionnaireChoiceDescription","QuestionnaireChoices","QuestionnaireDescription","QuestionnaireError","QuestionnaireInput","QuestionnaireItem","QuestionnaireNext","QuestionnairePrevious","QuestionnaireProgress","QuestionnaireSkip","QuestionnaireSubmit","QuestionnaireTitle"],
      examples: [{ Component: lazy(() => import("../examples/januna/QuestionnaireDemo")), source: QuestionnaireDemoSrc }],
    },
    {
      name: "Dialog",
      slug: "dialog",
      group: "Overlays",
      imports: ["Dialog","DialogClose","DialogContent","DialogDescription","DialogFooter","DialogHeader","DialogOverlay","DialogPortal","DialogTitle","DialogTrigger"],
      examples: [{ Component: lazy(() => import("../examples/januna/DialogDemo")), source: DialogDemoSrc }],
    },
    {
      name: "Alert Dialog",
      slug: "alert-dialog",
      group: "Overlays",
      imports: ["AlertDialog","AlertDialogAction","AlertDialogCancel","AlertDialogContent","AlertDialogDescription","AlertDialogFooter","AlertDialogHeader","AlertDialogMedia","AlertDialogOverlay","AlertDialogPortal","AlertDialogTitle","AlertDialogTrigger"],
      examples: [{ Component: lazy(() => import("../examples/januna/AlertDialogDemo")), source: AlertDialogDemoSrc }],
    },
    {
      name: "Sheet",
      slug: "sheet",
      group: "Overlays",
      imports: ["Sheet","SheetTrigger","SheetClose","SheetContent","SheetHeader","SheetFooter","SheetTitle","SheetDescription"],
      examples: [{ Component: lazy(() => import("../examples/januna/SheetDemo")), source: SheetDemoSrc }],
    },
    {
      name: "Drawer",
      slug: "drawer",
      group: "Overlays",
      imports: ["Drawer","DrawerPortal","DrawerOverlay","DrawerSwipeHandle","DrawerTrigger","DrawerClose","DrawerContent","DrawerHeader","DrawerFooter","DrawerTitle","DrawerDescription"],
      examples: [{ Component: lazy(() => import("../examples/januna/DrawerDemo")), source: DrawerDemoSrc }],
    },
    {
      name: "Popover",
      slug: "popover",
      group: "Overlays",
      imports: ["Popover","PopoverContent","PopoverDescription","PopoverHeader","PopoverTitle","PopoverTrigger"],
      examples: [{ Component: lazy(() => import("../examples/januna/PopoverDemo")), source: PopoverDemoSrc }],
    },
    {
      name: "Hover Card",
      slug: "hover-card",
      group: "Overlays",
      imports: ["HoverCard","HoverCardTrigger","HoverCardContent"],
      examples: [{ Component: lazy(() => import("../examples/januna/HoverCardDemo")), source: HoverCardDemoSrc }],
    },
    {
      name: "Tooltip",
      slug: "tooltip",
      group: "Overlays",
      imports: ["Tooltip","TooltipTrigger","TooltipContent","TooltipProvider"],
      examples: [{ Component: lazy(() => import("../examples/januna/TooltipDemo")), source: TooltipDemoSrc }],
    },
    {
      name: "Dropdown Menu",
      slug: "dropdown-menu",
      group: "Overlays",
      imports: ["DropdownMenu","DropdownMenuPortal","DropdownMenuTrigger","DropdownMenuContent","DropdownMenuGroup","DropdownMenuLabel","DropdownMenuItem","DropdownMenuCheckboxItem","DropdownMenuRadioGroup","DropdownMenuRadioItem","DropdownMenuSeparator","DropdownMenuShortcut","DropdownMenuSub","DropdownMenuSubTrigger","DropdownMenuSubContent"],
      examples: [{ Component: lazy(() => import("../examples/januna/DropdownMenuDemo")), source: DropdownMenuDemoSrc }],
    },
    {
      name: "Context Menu",
      slug: "context-menu",
      group: "Overlays",
      imports: ["ContextMenu","ContextMenuTrigger","ContextMenuContent","ContextMenuItem","ContextMenuCheckboxItem","ContextMenuRadioItem","ContextMenuLabel","ContextMenuSeparator","ContextMenuShortcut","ContextMenuGroup","ContextMenuPortal","ContextMenuSub","ContextMenuSubContent","ContextMenuSubTrigger","ContextMenuRadioGroup"],
      examples: [{ Component: lazy(() => import("../examples/januna/ContextMenuDemo")), source: ContextMenuDemoSrc }],
    },
    {
      name: "Menubar",
      slug: "menubar",
      group: "Overlays",
      imports: ["Menubar","MenubarPortal","MenubarMenu","MenubarTrigger","MenubarContent","MenubarGroup","MenubarSeparator","MenubarLabel","MenubarItem","MenubarShortcut","MenubarCheckboxItem","MenubarRadioGroup","MenubarRadioItem","MenubarSub","MenubarSubTrigger","MenubarSubContent"],
      examples: [{ Component: lazy(() => import("../examples/januna/MenubarDemo")), source: MenubarDemoSrc }],
    },
    {
      name: "Navigation Menu",
      slug: "navigation-menu",
      group: "Overlays",
      imports: ["NavigationMenu","NavigationMenuContent","NavigationMenuIndicator","NavigationMenuItem","NavigationMenuLink","NavigationMenuList","NavigationMenuTrigger","NavigationMenuPositioner"],
      examples: [{ Component: lazy(() => import("../examples/januna/NavigationMenuDemo")), source: NavigationMenuDemoSrc }],
    },
    {
      name: "Command",
      slug: "command",
      group: "Overlays",
      imports: ["Command","CommandDialog","CommandInput","CommandList","CommandEmpty","CommandGroup","CommandItem","CommandShortcut","CommandSeparator"],
      examples: [{ Component: lazy(() => import("../examples/januna/CommandDemo")), source: CommandDemoSrc }],
    },
    {
      name: "Toast",
      slug: "toast",
      group: "Overlays",
      imports: ["Toaster","Toast","ToastAction","ToastClose","ToastContent","ToastDescription","ToastPortal","ToastProvider","ToastTitle","ToastViewport"],
      examples: [{ Component: lazy(() => import("../examples/januna/ToastDemo")), source: ToastDemoSrc }],
    },
    {
      name: "Accordion",
      slug: "accordion",
      group: "Disclosure",
      imports: ["Accordion","AccordionItem","AccordionTrigger","AccordionContent"],
      examples: [{ Component: lazy(() => import("../examples/januna/AccordionDemo")), source: AccordionDemoSrc }],
    },
    {
      name: "Collapsible",
      slug: "collapsible",
      group: "Disclosure",
      imports: ["Collapsible","CollapsibleTrigger","CollapsibleContent"],
      examples: [{ Component: lazy(() => import("../examples/januna/CollapsibleDemo")), source: CollapsibleDemoSrc }],
    },
    {
      name: "Tabs",
      slug: "tabs",
      group: "Disclosure",
      imports: ["Tabs","TabsList","TabsTrigger","TabsContent"],
      examples: [{ Component: lazy(() => import("../examples/januna/TabsDemo")), source: TabsDemoSrc }],
    },
    {
      name: "Alert",
      slug: "alert",
      group: "Feedback",
      imports: ["Alert","AlertTitle","AlertDescription","AlertAction"],
      examples: [{ Component: lazy(() => import("../examples/januna/AlertDemo")), source: AlertDemoSrc }],
    },
    {
      name: "Badge",
      slug: "badge",
      group: "Feedback",
      imports: ["Badge"],
      examples: [{ Component: lazy(() => import("../examples/januna/BadgeDemo")), source: BadgeDemoSrc }],
    },
    {
      name: "Progress",
      slug: "progress",
      group: "Feedback",
      imports: ["Progress","ProgressTrack","ProgressIndicator","ProgressLabel","ProgressValue"],
      examples: [{ Component: lazy(() => import("../examples/januna/ProgressDemo")), source: ProgressDemoSrc }],
    },
    {
      name: "Spinner",
      slug: "spinner",
      group: "Feedback",
      imports: ["Spinner"],
      examples: [{ Component: lazy(() => import("../examples/januna/SpinnerDemo")), source: SpinnerDemoSrc }],
    },
    {
      name: "Skeleton",
      slug: "skeleton",
      group: "Feedback",
      imports: ["Skeleton"],
      examples: [{ Component: lazy(() => import("../examples/januna/SkeletonDemo")), source: SkeletonDemoSrc }],
    },
    {
      name: "Empty",
      slug: "empty",
      group: "Feedback",
      imports: ["Empty","EmptyHeader","EmptyTitle","EmptyDescription","EmptyContent","EmptyMedia"],
      examples: [{ Component: lazy(() => import("../examples/januna/EmptyDemo")), source: EmptyDemoSrc }],
    },
    {
      name: "Marker",
      slug: "marker",
      group: "Feedback",
      imports: ["Marker","MarkerIcon","MarkerContent"],
      examples: [{ Component: lazy(() => import("../examples/januna/MarkerDemo")), source: MarkerDemoSrc }],
    },
    {
      name: "Table",
      slug: "table",
      group: "Data",
      imports: ["Table","TableHeader","TableBody","TableFooter","TableHead","TableRow","TableCell","TableCaption"],
      examples: [{ Component: lazy(() => import("../examples/januna/TableDemo")), source: TableDemoSrc }],
    },
    {
      name: "Chart",
      slug: "chart",
      group: "Data",
      imports: ["ChartContainer","ChartTooltip","ChartTooltipContent","ChartLegend","ChartLegendContent","ChartStyle"],
      examples: [{ Component: lazy(() => import("../examples/januna/ChartDemo")), source: ChartDemoSrc }],
    },
    {
      name: "Pagination",
      slug: "pagination",
      group: "Data",
      imports: ["Pagination","PaginationContent","PaginationEllipsis","PaginationItem","PaginationLink","PaginationNext","PaginationPrevious"],
      examples: [{ Component: lazy(() => import("../examples/januna/PaginationDemo")), source: PaginationDemoSrc }],
    },
    {
      name: "Breadcrumb",
      slug: "breadcrumb",
      group: "Data",
      imports: ["Breadcrumb","BreadcrumbList","BreadcrumbItem","BreadcrumbLink","BreadcrumbPage","BreadcrumbSeparator","BreadcrumbEllipsis"],
      examples: [{ Component: lazy(() => import("../examples/januna/BreadcrumbDemo")), source: BreadcrumbDemoSrc }],
    },
    {
      name: "Avatar",
      slug: "avatar",
      group: "Data",
      imports: ["Avatar","AvatarImage","AvatarFallback","AvatarGroup","AvatarGroupCount","AvatarBadge"],
      examples: [{ Component: lazy(() => import("../examples/januna/AvatarDemo")), source: AvatarDemoSrc }],
    },
    {
      name: "Card",
      slug: "card",
      group: "Data",
      imports: ["Card","CardHeader","CardFooter","CardTitle","CardAction","CardDescription","CardContent"],
      examples: [{ Component: lazy(() => import("../examples/januna/CardDemo")), source: CardDemoSrc }],
    },
    {
      name: "Item",
      slug: "item",
      group: "Data",
      imports: ["Item","ItemMedia","ItemContent","ItemActions","ItemGroup","ItemSeparator","ItemTitle","ItemDescription","ItemHeader","ItemFooter"],
      examples: [{ Component: lazy(() => import("../examples/januna/ItemDemo")), source: ItemDemoSrc }],
    },
    {
      name: "Carousel",
      slug: "carousel",
      group: "Data",
      imports: ["CarouselApi","Carousel","CarouselContent","CarouselItem","CarouselPrevious","CarouselNext"],
      examples: [{ Component: lazy(() => import("../examples/januna/CarouselDemo")), source: CarouselDemoSrc }],
    },
    {
      name: "Separator",
      slug: "separator",
      group: "Layout",
      imports: ["Separator"],
      examples: [{ Component: lazy(() => import("../examples/januna/SeparatorDemo")), source: SeparatorDemoSrc }],
    },
    {
      name: "Aspect Ratio",
      slug: "aspect-ratio",
      group: "Layout",
      imports: ["AspectRatio"],
      examples: [{ Component: lazy(() => import("../examples/januna/AspectRatioDemo")), source: AspectRatioDemoSrc }],
    },
    {
      name: "Scroll Area",
      slug: "scroll-area",
      group: "Layout",
      imports: ["ScrollArea","ScrollBar"],
      examples: [{ Component: lazy(() => import("../examples/januna/ScrollAreaDemo")), source: ScrollAreaDemoSrc }],
    },
    {
      name: "Resizable",
      slug: "resizable",
      group: "Layout",
      imports: ["ResizableHandle","ResizablePanel","ResizablePanelGroup"],
      examples: [{ Component: lazy(() => import("../examples/januna/ResizableDemo")), source: ResizableDemoSrc }],
    },
    {
      name: "Sidebar",
      slug: "sidebar",
      group: "Layout",
      imports: ["Sidebar","SidebarContent","SidebarFooter","SidebarGroup","SidebarGroupAction","SidebarGroupContent","SidebarGroupLabel","SidebarHeader","SidebarInput","SidebarInset","SidebarMenu","SidebarMenuAction","SidebarMenuBadge","SidebarMenuButton","SidebarMenuItem","SidebarMenuSkeleton","SidebarMenuSub","SidebarMenuSubButton","SidebarMenuSubItem","SidebarProvider","SidebarRail","SidebarSeparator","SidebarTrigger"],
      examples: [{ Component: lazy(() => import("../examples/januna/SidebarDemo")), source: SidebarDemoSrc }],
    },
    {
      name: "Direction",
      slug: "direction",
      group: "Layout",
      imports: [],
      examples: [{ Component: lazy(() => import("../examples/januna/DirectionDemo")), source: DirectionDemoSrc }],
    },
    {
      name: "Message",
      slug: "message",
      group: "Chat",
      imports: ["MessageGroup","Message","MessageAvatar","MessageContent","MessageFooter","MessageHeader"],
      examples: [{ Component: lazy(() => import("../examples/januna/MessageDemo")), source: MessageDemoSrc }],
    },
    {
      name: "Message Scroller",
      slug: "message-scroller",
      group: "Chat",
      imports: ["MessageScrollerProvider","MessageScroller","MessageScrollerViewport","MessageScrollerContent","MessageScrollerItem","MessageScrollerButton"],
      examples: [{ Component: lazy(() => import("../examples/januna/MessageScrollerDemo")), source: MessageScrollerDemoSrc }],
    },
    {
      name: "Bubble",
      slug: "bubble",
      group: "Chat",
      imports: ["BubbleGroup","Bubble","BubbleContent","BubbleReactions"],
      examples: [{ Component: lazy(() => import("../examples/januna/BubbleDemo")), source: BubbleDemoSrc }],
    },
    {
      name: "Attachment",
      slug: "attachment",
      group: "Chat",
      imports: ["Attachment","AttachmentGroup","AttachmentMedia","AttachmentContent","AttachmentTitle","AttachmentDescription","AttachmentActions","AttachmentAction","AttachmentTrigger"],
      examples: [{ Component: lazy(() => import("../examples/januna/AttachmentDemo")), source: AttachmentDemoSrc }],
    },
  ],
};
