// The props tables, generated by scripts/gen-props.mjs at build time and
// bundled. Never edited by hand.

import doc from "./props.json";
import type { PkgId } from "./types";

export type PropDoc = {
  name: string;
  type: string;
  required: boolean;
  defaultValue?: string;
  description: string;
};

export type ComponentDoc = { description: string; props: PropDoc[] };

type PkgDoc = { name: string; version: string; components: Record<string, ComponentDoc> };

const DOC = doc as unknown as { generatedAt: string; packages: Record<PkgId, PkgDoc> };

/** The version the tables were generated from — the one this catalog documents. */
export function pkgVersion(id: PkgId): string {
  return DOC.packages[id]?.version ?? "?";
}

export function componentDoc(id: PkgId, displayName: string): ComponentDoc | undefined {
  return DOC.packages[id]?.components[displayName];
}
