/* Turn a package's foundations (src/foundations/*.ts) into the CSS the
 * components and apps read. One file per foundation, generated, so the
 * TypeScript is the only place a value is written.
 *
 *   bun run scripts/gen-foundations.ts januna */
import { writeFileSync } from "node:fs";

const ID = process.argv[2];
if (!ID) throw new Error("usage: gen-foundations.ts <package id>");
const ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");
const PREFIX: Record<string, string> = { januna: "jan", ticketova: "tova", internal: "int" };
const p = PREFIX[ID];
if (!p) throw new Error(`no token prefix for ${ID}`);

const { BACKGROUNDS, SCALES, STEPS, SEMANTIC } = await import(`${ROOT}/packages/${ID}/src/foundations/colors.ts`);

const vars: string[] = [];
const theme: string[] = [];
for (const [step, bg] of Object.entries(BACKGROUNDS)) {
  vars.push(`  --${p}-background-${step}: ${(bg as { value: string }).value};`);
  theme.push(`  --color-background-${step}: var(--${p}-background-${step});`);
}
for (const s of SCALES) {
  for (const step of STEPS) {
    vars.push(`  --${p}-${s.id}-${step}: ${s.steps[step]};`);
    theme.push(`  --color-${s.id}-${step}: var(--${p}-${s.id}-${step});`);
  }
}

const sem: string[] = [];
const semTheme: string[] = [];
for (const g of SEMANTIC) {
  for (const t of g.tokens) {
    sem.push(`  --${p}-${t.token}: var(--${p}-${t.ref});`);
    semTheme.push(`  --color-${t.token}: var(--${p}-${t.token});`);
  }
}

const css = `/* Generated by scripts/gen-foundations.ts from src/foundations/colors.ts.
   Do not edit: change the TypeScript and run \`bun run foundations\`.

   The scales as custom properties, on :root for an app that wears the brand
   and on [data-brand="${ID}"] for a page that shows more than one; and the
   same scales as Tailwind colours, so \`bg-green-700\` or \`border-gray-400\`
   name a step of the system. Then the semantic layer on top: surface,
   content, accent, status, stroke — bg-surface-secondary,
   text-content-tertiary — each one step of one scale. Tailwind's own
   palette is cleared first: the only colours an app can reach for are
   these. */

:root,
[data-brand="${ID}"] {
${vars.join("\n")}

${sem.join("\n")}
}

@theme inline {
  --color-*: initial;
  --color-transparent: transparent;
  --color-current: currentColor;
  --color-white: #ffffff;
  --color-black: #000000;
${theme.join("\n")}

${semTheme.join("\n")}
}
`;
writeFileSync(`${ROOT}/packages/${ID}/src/colors.css`, css);
console.log(`packages/${ID}/src/colors.css: ${SCALES.length} scales, ${vars.length} tokens`);

/* ── typography ──────────────────────────────────────────────────────── */
{
  const { GROUPS, FACES } = await import(`${ROOT}/packages/${ID}/src/foundations/typography.ts`);
  const out: string[] = [
    `/* Generated by scripts/gen-foundations.ts from src/foundations/typography.ts.`,
    `   Do not edit: change the TypeScript and run \`bun run foundations\`.`,
    ``,
    `   One class per style, setting size, line height, tracking and weight`,
    `   together. <strong> inside a style is its modifier. */`,
    ``,
    `@theme inline {`,
    `  --font-sans: ${FACES.sans.stack};`,
    `  --font-mono: ${FACES.mono.stack};`,
    `  --font-heading: var(--font-sans);`,
    `}`,
    ``,
  ];
  for (const g of GROUPS) {
    for (const st of g.styles) {
      out.push(
        `@utility ${st.cls} {`,
        `  font-family: var(--font-${st.family});`,
        `  font-size: ${st.size}px;`,
        `  line-height: ${st.line}px;`,
        `  letter-spacing: ${st.tracking};`,
        `  font-weight: ${st.weight};`,
        ...(st.family === "mono" ? [`  font-variant-numeric: tabular-nums;`] : []),
        `  & strong {`,
        ...(g.strong === "subtle"
          ? [`    font-weight: 400;`, `    color: var(--${p}-gray-900);`]
          : [`    font-weight: 500;`, `    color: var(--${p}-gray-1000);`]),
        `  }`,
        `}`,
        ``,
      );
    }
  }
  writeFileSync(`${ROOT}/packages/${ID}/src/typography.css`, out.join("\n"));
  console.log(`packages/${ID}/src/typography.css: ${GROUPS.reduce((n: number, g: { styles: unknown[] }) => n + g.styles.length, 0)} styles`);
}

/* ── materials ───────────────────────────────────────────────────────── */
{
  const { SURFACE, FLOATING, TINTS } = await import(`${ROOT}/packages/${ID}/src/foundations/materials.ts`);
  const all = [...SURFACE, ...FLOATING, ...TINTS];
  const out: string[] = [
    `/* Generated by scripts/gen-foundations.ts from src/foundations/materials.ts.`,
    `   Do not edit: change the TypeScript and run \`bun run foundations\`.`,
    ``,
    `   One class per material: radius, fill, stroke and shadow together. The`,
    `   shadows are also Tailwind shadows (shadow-menu) for the rare case a`,
    `   component needs the lift without the rest. */`,
    ``,
    `:root,`,
    `[data-brand="${ID}"] {`,
    ...all.map((m: { cls: string; shadow: string; stroke: string }) => `  --${p}-shadow-${m.cls.replace("material-", "")}: ${m.stroke}${m.shadow === "none" ? "" : `, ${m.shadow}`};`),
    `}`,
    ``,
    `@theme inline {`,
    ...all.map((m: { cls: string }) => `  --shadow-${m.cls.replace("material-", "")}: var(--${p}-shadow-${m.cls.replace("material-", "")});`),
    `}`,
    ``,
  ];
  for (const m of all) {
    out.push(
      `@utility ${m.cls} {`,
      `  border-radius: ${m.radius}px;`,
      `  background: ${m.fill};`,
      `  box-shadow: var(--${p}-shadow-${m.cls.replace("material-", "")});`,
      `}`,
      ``,
    );
  }
  writeFileSync(`${ROOT}/packages/${ID}/src/materials.css`, out.join("\n"));
  console.log(`packages/${ID}/src/materials.css: ${all.length} materials`);
}

/* ── layout: spacing, radius, motion ─────────────────────────────────── */
{
  const { SPACING, RADIUS, MOTION } = await import(`${ROOT}/packages/${ID}/src/foundations/layout.ts`);
  type T = { token: string; value: string };
  const all: T[] = [...SPACING, ...RADIUS, ...MOTION];
  const out: string[] = [
    `/* Generated by scripts/gen-foundations.ts from src/foundations/layout.ts.`,
    `   Do not edit: change the TypeScript and run \`bun run foundations\`.`,
    ``,
    `   The spacing set, the corners and the motion, as custom properties and`,
    `   as Tailwind tokens: p-space-4, rounded-regular, ease-out-brand,`,
    `   duration-base. */`,
    ``,
    `:root,`,
    `[data-brand="${ID}"] {`,
    ...all.map((t) => `  --${p}-${t.token}: ${t.value};`),
    `}`,
    ``,
    `@theme inline {`,
    ...SPACING.map((t: T) => `  --spacing-${t.token}: var(--${p}-${t.token});`),
    ...RADIUS.map((t: T) => `  --radius-${t.token.replace("radius-", "")}: var(--${p}-${t.token});`),
    ...MOTION.filter((t: T) => t.token.startsWith("ease")).map((t: T) => `  --ease-brand: var(--${p}-${t.token});`),
    ...MOTION.filter((t: T) => t.token.startsWith("duration")).map((t: T) => `  --duration-${t.token.replace("duration-", "")}: var(--${p}-${t.token});`),
    `}`,
    ``,
    `@media (prefers-reduced-motion: reduce) {`,
    `  :root,`,
    `  [data-brand="${ID}"] {`,
    ...MOTION.filter((t: T) => t.token.startsWith("duration")).map((t: T) => `    --${p}-${t.token}: 0ms;`),
    `  }`,
    `}`,
    ``,
  ];
  writeFileSync(`${ROOT}/packages/${ID}/src/layout.css`, out.join("\n"));
  console.log(`packages/${ID}/src/layout.css: ${all.length} tokens`);
}
