/* Internal is Ovadev in light mode. Its one stylesheet of its own,
 * packages/internal/src/internal.css, is generated from Ovadev's so it can
 * never drift: the light block of colors.css as the default for a page that
 * sets no data-theme, and every --ova-* token Ovadev declares under its old
 * --int-* name, for the tools' stylesheets that still write those.
 *
 *   bun run scripts/gen-internal.ts */
import { readFileSync, writeFileSync } from "node:fs";

const ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");
const OVA = `${ROOT}/packages/ovadev/src`;

const colors = readFileSync(`${OVA}/colors.css`, "utf8");
const start = colors.indexOf(':root[data-theme="light"]');
if (start < 0) throw new Error("ovadev colors.css has no light block: run its foundations first");
const open = colors.indexOf("{", start);
const light = colors.slice(open + 1, colors.indexOf("\n}", open)).replace(/^\n+/, "").trimEnd();

const tokens = new Set<string>();
for (const f of ["colors.css", "typography.css", "materials.css", "layout.css", "theme.css"]) {
  for (const m of readFileSync(`${OVA}/${f}`, "utf8").matchAll(/(--ova-[a-z0-9-]+):/g)) tokens.add(m[1]!);
}
const aliases = [...tokens].sort().map((t) => `  ${t.replace("--ova-", "--int-")}: var(${t});`);

const css = `/* Generated by scripts/gen-internal.ts from packages/ovadev/src.
   Do not edit: change Ovadev and run \`bun run build\`.

   A tool sets figures, IDs and dates in a real monospace: Geist Mono, where
   Ovadev's mono role is Geist with tabular figures. Every *-mono style reads
   --font-mono, so the one variable changes them all. */

@import "@fontsource-variable/geist-mono";

:root {
  --font-mono: "Geist Mono Variable", "Geist Mono", ui-monospace, "SF Mono", Menlo, monospace;
}

/* Light is Internal's default: a page with no data-theme wears Ovadev's
   light mode. data-theme="dark" (or "system") on <html> hands the choice
   back to Ovadev's own rules. */

:root:not([data-theme]) {
${light}
}

/* The names the tools' stylesheets were written with. Declared wherever the
   tokens are, so a part of the page that switches mode switches these too. */
:root,
[data-theme],
[data-brand] {
${aliases.join("\n")}
}
`;
writeFileSync(`${ROOT}/packages/internal/src/internal.css`, css);
console.log(`packages/internal/src/internal.css: light default, ${aliases.length} --int-* aliases`);
