/* Turn a package's foundations (src/foundations/*.ts) into the CSS the
 * components and apps read. One file per foundation, generated, so the
 * TypeScript is the only place a value is written.
 *
 *   bun run scripts/gen-foundations.ts januna */
import { writeFileSync } from "node:fs";

const ID = process.argv[2];
if (!ID) throw new Error("usage: gen-foundations.ts <package id>");
const ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");
const PREFIX: Record<string, string> = { januna: "jan", ticketova: "tova" };
const p = PREFIX[ID];
if (!p) throw new Error(`no token prefix for ${ID}`);

const { BACKGROUNDS, SCALES, STEPS } = await import(`${ROOT}/packages/${ID}/src/foundations/colors.ts`);

const vars: string[] = [];
const theme: string[] = [];
for (const [step, bg] of Object.entries(BACKGROUNDS)) {
  vars.push(`  --${p}-background-${step}: ${(bg as { value: string }).value};`);
  theme.push(`  --color-background-${step}: var(--${p}-background-${step});`);
}
for (const s of SCALES) {
  for (const step of STEPS) {
    vars.push(`  --${p}-${s.id}-${step}: ${s.steps[step]};`);
    theme.push(`  --color-${s.id}-${step}: var(--${p}-${s.id}-${step});`);
  }
}

const css = `/* Generated by scripts/gen-foundations.ts from src/foundations/colors.ts.
   Do not edit: change the TypeScript and run \`bun run foundations\`.

   The scales as custom properties, on :root for an app that wears the brand
   and on [data-brand="${ID}"] for a page that shows more than one; and the
   same scales as Tailwind colours, so \`bg-green-700\` or \`border-gray-400\`
   name a step of the system. Tailwind's own palette is cleared first: the
   only colours an app can reach for are these. */

:root,
[data-brand="${ID}"] {
${vars.join("\n")}
}

@theme inline {
  --color-*: initial;
  --color-transparent: transparent;
  --color-current: currentColor;
  --color-white: #ffffff;
  --color-black: #000000;
${theme.join("\n")}
}
`;
writeFileSync(`${ROOT}/packages/${ID}/src/colors.css`, css);
console.log(`packages/${ID}/src/colors.css: ${SCALES.length} scales, ${vars.length} tokens`);
