/* The catalog's registry for a shadcn package: one entry per component in
 * packages/<id>/src/components/ui, pointing at a demo in
 * site/src/examples/<id>/<Name>Demo.tsx.
 *
 * The demos are imported lazily. They pull in the package and its Tailwind
 * classes, which the catalog's own page never renders — they run inside the
 * preview frame (site/preview.html), so the main bundle carries only their
 * source text.
 *
 *   bun run scripts/gen-shadcn-registry.ts januna */
import { writeFileSync } from "node:fs";
import { BRANDS, GROUPS, ROOT, componentsOf, pascal } from "./lib/catalog";

const ID = process.argv[2];
if (!ID) throw new Error("usage: gen-shadcn-registry.ts <package id>");
const meta = BRANDS[ID];
if (!meta) throw new Error(`no catalog metadata for ${ID}`);

const components = componentsOf(ID);
const lines: string[] = [
  `/* The ${meta.name} catalog. Generated by scripts/gen-shadcn-registry.ts from`,
  `   packages/${ID}/src/components/ui — do not edit; add a demo under`,
  `   site/src/examples/${ID}/ and run the script. */`,
  `import { lazy } from "react";`,
  `import type { Pkg } from "../types";`,
  ...components.map((c) => `import ${pascal(c.slug)}DemoSrc from "../examples/${ID}/${pascal(c.slug)}Demo.tsx?raw";`),
  ``,
  `export const ${ID}: Pkg = {`,
  `  id: "${ID}",`,
  `  name: "${meta.name}",`,
  `  pkg: "${meta.pkg}",`,
  `  frame: true,`,
  `  groups: [${GROUPS.map(([g]) => JSON.stringify(g)).join(", ")}],`,
  `  entries: [`,
];
for (const c of components) {
  const P = pascal(c.slug);
  lines.push(
    `    {`,
    `      name: ${JSON.stringify(c.name)},`,
    `      slug: ${JSON.stringify(c.slug)},`,
    `      group: ${JSON.stringify(c.group)},`,
    `      imports: ${JSON.stringify(c.exports)},`,
    `      examples: [{ Component: lazy(() => import("../examples/${ID}/${P}Demo")), source: ${P}DemoSrc }],`,
    `    },`,
  );
}
lines.push(`  ],`, `};`, ``);
writeFileSync(`${ROOT}/site/src/registry/${ID}.ts`, lines.join("\n"));
console.log(`site/src/registry/${ID}.ts: ${components.length} entries`);
