/* The catalog's registry for a shadcn package: one entry per component in
 * packages/<id>/src/components/ui, pointing at a demo in
 * site/src/examples/<id>/<Name>Demo.tsx.
 *
 * The demos are imported lazily. They pull in the package and its Tailwind
 * classes, which the catalog's own page never renders — they run inside the
 * preview frame (site/preview.html), so the main bundle carries only their
 * source text.
 *
 *   bun run scripts/gen-shadcn-registry.ts januna */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const ID = process.argv[2];
if (!ID) throw new Error("usage: gen-shadcn-registry.ts <package id>");
const ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");

const NAMES: Record<string, { name: string; pkg: string }> = {
  januna: { name: "Januna", pkg: "@ovadev-gmbh/ui-januna" },
  ticketova: { name: "TICKETOVA", pkg: "@ovadev-gmbh/ui-ticketova" },
};
const meta = NAMES[ID];
if (!meta) throw new Error(`no catalog metadata for ${ID}`);

/** Sidebar groups, in order, and which slug sits in which. */
const GROUPS: [string, string[]][] = [
  ["Actions", ["button", "button-group", "toggle", "toggle-group", "kbd"]],
  ["Forms", ["input", "input-group", "input-otp", "textarea", "label", "field", "checkbox", "radio-group", "switch", "select", "native-select", "combobox", "slider", "calendar", "questionnaire"]],
  ["Overlays", ["dialog", "alert-dialog", "sheet", "drawer", "popover", "hover-card", "tooltip", "dropdown-menu", "context-menu", "menubar", "navigation-menu", "command", "toast"]],
  ["Disclosure", ["accordion", "collapsible", "tabs"]],
  ["Feedback", ["alert", "badge", "progress", "spinner", "skeleton", "empty", "marker"]],
  ["Data", ["table", "chart", "pagination", "breadcrumb", "avatar", "card", "item", "carousel"]],
  ["Layout", ["separator", "aspect-ratio", "scroll-area", "resizable", "sidebar", "direction"]],
  ["Chat", ["message", "message-scroller", "bubble", "attachment"]],
];
const groupOf = new Map(GROUPS.flatMap(([g, slugs]) => slugs.map((s) => [s, g] as const)));

/** Words that stay in caps when a slug becomes a name. */
const CAPS: Record<string, string> = { otp: "OTP" };
const pascal = (slug: string) => slug.split("-").map((w) => w[0]!.toUpperCase() + w.slice(1)).join("");
const title = (slug: string) => slug.split("-").map((w) => CAPS[w] ?? w[0]!.toUpperCase() + w.slice(1)).join(" ");

/** The component names a file exports — its closing `export { … }` block,
 *  minus the helpers (variants, hooks) that start lowercase. */
function exportsOf(src: string): string[] {
  const block = src.match(/export \{([^}]+)\}\s*$/);
  if (!block) return [];
  return block[1]!
    .split(",")
    .map((s) => s.trim().replace(/^type /, "").split(/\s+as\s+/).pop()!)
    .filter((n) => n && /^[A-Z]/.test(n));
}

const dir = `${ROOT}/packages/${ID}/src/components/ui`;
const slugs = readdirSync(dir).filter((f) => f.endsWith(".tsx")).map((f) => f.replace(/\.tsx$/, ""));
const missing = slugs.filter((s) => !groupOf.has(s));
if (missing.length) throw new Error(`ungrouped components: ${missing.join(", ")}`);

const ordered = GROUPS.flatMap(([, s]) => s).filter((s) => slugs.includes(s));
const lines: string[] = [
  `/* The ${meta.name} catalog. Generated by scripts/gen-shadcn-registry.ts from`,
  `   packages/${ID}/src/components/ui — do not edit; add a demo under`,
  `   site/src/examples/${ID}/ and run the script. */`,
  `import { lazy } from "react";`,
  `import type { Pkg } from "../types";`,
  ...ordered.map((s) => `import ${pascal(s)}DemoSrc from "../examples/${ID}/${pascal(s)}Demo.tsx?raw";`),
  ``,
  `export const ${ID}: Pkg = {`,
  `  id: "${ID}",`,
  `  name: "${meta.name}",`,
  `  pkg: "${meta.pkg}",`,
  `  frame: true,`,
  `  groups: [${GROUPS.map(([g]) => JSON.stringify(g)).join(", ")}],`,
  `  entries: [`,
];
for (const s of ordered) {
  const imports = exportsOf(readFileSync(`${dir}/${s}.tsx`, "utf8"));
  const P = pascal(s);
  lines.push(
    `    {`,
    `      name: ${JSON.stringify(title(s))},`,
    `      slug: ${JSON.stringify(s)},`,
    `      group: ${JSON.stringify(groupOf.get(s))},`,
    `      imports: ${JSON.stringify(imports)},`,
    `      examples: [{ Component: lazy(() => import("../examples/${ID}/${P}Demo")), source: ${P}DemoSrc }],`,
    `    },`,
  );
}
lines.push(`  ],`, `};`, ``);
writeFileSync(`${ROOT}/site/src/registry/${ID}.ts`, lines.join("\n"));
console.log(`site/src/registry/${ID}.ts: ${ordered.length} entries`);
