/* The catalog's registry for a shadcn package: one entry per component in
 * packages/<id>/src/components/ui, pointing at a demo in
 * site/src/examples/<id>/<Name>Demo.tsx.
 *
 * A component with a doc (site/src/docs/<id>/<slug>.ts) also gets one example
 * per section that names one, from site/src/examples/<id>/<slug>/<name>.tsx,
 * and carries the doc itself for its page.
 *
 * The demos are imported lazily. They pull in the package and its Tailwind
 * classes, which the catalog's own page never renders — they run inside the
 * preview frame (site/preview.html), so the main bundle carries only their
 * source text.
 *
 *   bun run scripts/gen-shadcn-registry.ts januna */
import { existsSync, writeFileSync } from "node:fs";
import type { Doc } from "../site/src/types";
import { BRANDS, GROUPS, ROOT, componentsOf, pascal } from "./lib/catalog";

const ID = process.argv[2];
if (!ID) throw new Error("usage: gen-shadcn-registry.ts <package id>");
const meta = BRANDS[ID];
if (!meta) throw new Error(`no catalog metadata for ${ID}`);

const components = componentsOf(ID);
const docs = new Map<string, Doc>();
for (const c of components) {
  const path = `${ROOT}/site/src/docs/${ID}/${c.slug}.ts`;
  if (!existsSync(path)) continue;
  const doc = (await import(path)).default as Doc;
  for (const s of doc.sections) {
    if (s.example && !existsSync(`${ROOT}/site/src/examples/${ID}/${c.slug}/${s.example}.tsx`)) {
      throw new Error(`${c.slug}: section "${s.title}" names examples/${ID}/${c.slug}/${s.example}.tsx, which does not exist`);
    }
  }
  docs.set(c.slug, doc);
}

const lines: string[] = [
  `/* The ${meta.name} catalog. Generated by scripts/gen-shadcn-registry.ts from`,
  `   packages/${ID}/src/components/ui and site/src/docs/${ID} — do not edit; add a`,
  `   demo under site/src/examples/${ID}/ or a doc under site/src/docs/${ID}/ and run`,
  `   the script. */`,
  `import { lazy } from "react";`,
  `import type { Pkg } from "../types";`,
  ...components.map((c) => `import ${pascal(c.slug)}DemoSrc from "../examples/${ID}/${pascal(c.slug)}Demo.tsx?raw";`),
  ...components.flatMap((c) => {
    const doc = docs.get(c.slug);
    if (!doc) return [];
    return [
      `import ${pascal(c.slug)}Doc from "../docs/${ID}/${c.slug}";`,
      ...doc.sections
        .filter((s) => s.example)
        .map((s) => `import ${pascal(c.slug)}${pascal(s.example!)}Src from "../examples/${ID}/${c.slug}/${s.example}.tsx?raw";`),
    ];
  }),
  ``,
  `export const ${ID}: Pkg = {`,
  `  id: "${ID}",`,
  `  name: "${meta.name}",`,
  `  pkg: "${meta.pkg}",`,
  `  frame: true,`,
  `  groups: [${GROUPS.map(([g]) => JSON.stringify(g)).join(", ")}],`,
  `  entries: [`,
];
for (const c of components) {
  const P = pascal(c.slug);
  const doc = docs.get(c.slug);
  const sectionExamples = (doc?.sections ?? [])
    .filter((s) => s.example)
    .map(
      (s) =>
        `        { name: ${JSON.stringify(s.example)}, Component: lazy(() => import("../examples/${ID}/${c.slug}/${s.example}")), source: ${P}${pascal(s.example!)}Src },`,
    );
  lines.push(
    `    {`,
    `      name: ${JSON.stringify(c.name)},`,
    `      slug: ${JSON.stringify(c.slug)},`,
    `      group: ${JSON.stringify(c.group)},`,
    `      imports: ${JSON.stringify(c.exports)},`,
    ...(doc
      ? [
          `      examples: [`,
          `        { Component: lazy(() => import("../examples/${ID}/${P}Demo")), source: ${P}DemoSrc },`,
          ...sectionExamples,
          `      ],`,
          `      doc: ${P}Doc,`,
        ]
      : [`      examples: [{ Component: lazy(() => import("../examples/${ID}/${P}Demo")), source: ${P}DemoSrc }],`]),
    `    },`,
  );
}
lines.push(`  ],`, `};`, ``);
writeFileSync(`${ROOT}/site/src/registry/${ID}.ts`, lines.join("\n"));
console.log(`site/src/registry/${ID}.ts: ${components.length} entries, ${docs.size} with docs`);
