/* After `shadcn add`: make a package's components importable from outside.
 *
 * The CLI writes `@/components/ui/button`-style imports, which only resolve
 * inside the package (tsconfig paths). A published package needs relative
 * ones, and an index that exports every component. Run with the package
 * directory as the argument; `bun run shadcn` in each package does. */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const pkg = resolve(process.argv[2] ?? ".");
const ui = resolve(pkg, "src/components/ui");
const files = readdirSync(ui).filter((f) => f.endsWith(".tsx")).sort();

let rewritten = 0;
for (const f of files) {
  const path = resolve(ui, f);
  const before = readFileSync(path, "utf8");
  const after = before
    .replace(/from "@\/components\/ui\/([^"]+)"/g, 'from "./$1"')
    .replace(/from "@\/lib\/([^"]+)"/g, 'from "../../lib/$1"')
    .replace(/from "@\/hooks\/([^"]+)"/g, 'from "../../hooks/$1"');
  if (after !== before) {
    writeFileSync(path, after);
    rewritten++;
  }
}

const index = [
  "/* Every component this package ships. Generated by scripts/shadcn-relativize.ts",
  "   from src/components/ui; add a component with `bun run shadcn`, not here. */",
  ...files.map((f) => `export * from "./components/ui/${f.replace(/\.tsx$/, "")}";`),
  'export { cn } from "./lib/utils";',
  'export { useIsMobile } from "./hooks/use-mobile";',
  'export * as colors from "./foundations/colors";',
  'export * as typography from "./foundations/typography";',
  'export * as materials from "./foundations/materials";',
  "",
].join("\n");
writeFileSync(resolve(pkg, "src/index.ts"), index);

console.log(`${pkg}: rewrote imports in ${rewritten} file(s), indexed ${files.length} component(s)`);
