/* The blocks this package ships, as the ./blocks subpath. Generated by
   scripts/gen-shadcn-registry.ts from src/blocks — add a file there and
   list it in scripts/lib/catalog.ts, not here. */
export * from "./blocks/app-shell";
export * from "./blocks/auth";
export * from "./blocks/error-page";
export * from "./blocks/stats";
