/* Put a class on a Base UI part without changing anything else about it.
 *
 * Base UI parts take `className` either as a string or as a function of the
 * part's own state, and both have to keep working — so the brand class is
 * prepended to whichever the caller passed. The result is cast back to the
 * part's own type, so the wrapper is invisible: same props, same generics,
 * same ref.
 *
 * Generated by scripts/gen-baseui.ts, and identical in all four packages —
 * the libraries stay independent, with no shared core to import. */
import { createElement, forwardRef } from "react";
import type { ElementType } from "react";

type ClassName = string | ((state: never) => string | undefined) | undefined;

const join = (brand: string, own: string | undefined) => (own ? `${brand} ${own}` : brand);

export function part<T>(Part: T, brand: string): T {
  const Wrapped = forwardRef<unknown, { className?: ClassName }>(function BrandPart(props, ref) {
    const own = props.className;
    const className =
      typeof own === "function" ? (state: never) => join(brand, own(state)) : join(brand, own);
    // `ref` first: on React 19 it arrives in props and wins, on React 18 the
    // forwarded one is the only one there is.
    return createElement(Part as unknown as ElementType, { ref, ...props, className });
  });
  Wrapped.displayName = brand;
  return Wrapped as unknown as T;
}
